In [1]:
import requests
import re
import pandas as pd
import numpy as np
import math
import json
from itertools import chain
import time
from datetime import datetime
from IPython.display import clear_output

In [2]:
url = f'https://diavgeia.gov.gr/luminapi/api/search/export?q=q:"ελληνικο"&fq=thematicCategory:"περιβαλλον"&fq=organizationUid:99201077&fq=unitUid:77540&decisionTypeUid:2.4.6.1&fq=submissionTimestamp:[DT(2022-01-01T00:00:00) TO DT(2023-01-01T23:59:59)]&fq=issueDate:[DT(2022-01-01T00:00:00) TO DT(2023-01-01T23:59:59)]&wt=json'

In [ ]:
# 99201077 - τεχνικό επιμελητήριο
# decisionTypeUid:2.4.6.1 πράξεις χωροταξικού σχεδιασμού
from datetime import date
from dateutil.relativedelta import relativedelta

start_date = date(2019, 1, 1)
end_date = date(2026, 1, 25)
current_date = start_date
results=[]
while current_date < end_date:
    u = f'https://diavgeia.gov.gr/luminapi/api/search/export?q=q:"ελληνικο"&fq=thematicCategory:"περιβαλλον"&fq=organizationUid:99201077&fq=unitUid:77540&decisionTypeUid:2.4.6.1&fq=submissionTimestamp:[DT({current_date}T00:01:00) TO DT({current_date + relativedelta(months=+6)}T00:00:00)]&fq=issueDate:[DT({current_date}T00:01:00) TO DT({current_date + relativedelta(months=+6)}T00:00:00)]&wt=json'

    d = requests.get(u).json()
    results.extend(d['decisionResultList'])
    print(f"Getting date: {current_date}")
    current_date += relativedelta(months=+6)

Getting date: 2019-01-01
Getting date: 2019-07-01
Getting date: 2020-01-01
Getting date: 2020-07-01
Getting date: 2021-01-01
Getting date: 2021-07-01
Getting date: 2022-01-01
Getting date: 2022-07-01
Getting date: 2023-01-01
Getting date: 2023-07-01
Getting date: 2024-01-01
Getting date: 2024-07-01
Getting date: 2025-01-01
Getting date: 2025-07-01
Getting date: 2026-01-01

In [4]:
len(results)

11710

In [5]:
terms = ["Α-Π1", "Α-Π2", "Α-Π3", "Α-Π4", "Α-Π5", "Α-Π6", "ΠΜ-Π1", "Α-Α1-1", "ΠΜ Α1", "ΠΜ Α2"]

In [6]:
term_gen = (term for term in terms)

In [7]:
next(term_gen)

'Α-Π1'

In [8]:
filtered_results = []
for item in results:
    if "μητροπολιτικ" in item['subject'].lower() and "ελληνικ" in item['subject'].lower():
        print(item['subject'])
        filtered_results.append(item)

Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: Εκτέλεση Γεωτεχνικών και Γεωφυσικών ερευνών, Γεωτεχνική αξιολόγηση και Γεωτεχνικές μελέτες θεμελίωσης στο χερσαίο τμήμα του Μητροπολιτικού πόλου Ελληνικού – Αγ;iου Κοσμά
Οικοδομική Άδεια (ν.4759/2020): ΕΡΓΑΣΙΕΣ ΑΠΟΚΑΤΑΣΤΑΣΗΣ ΚΕΛΥΦΟΥΣ TOY ΧΑΡΑΚΤΗΡΙΣΜΕΝΟΥ ΝΕΩΤΕΡΟΥ ΜΝΗΜΕΙΟΥ ΥΠΟΣΤΕΓΟΥ Γ' ΤΗΣ ΠΟΛΕΜΙΚΗΣ ΑΕΡΟΠΟΡΙΑΣ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΡΑΣΙΝΟΥ ΚΑΙ ΑΝΑΨΥΧΗΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓ. ΚΟΣΜΑ»
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΕΡΓΑΣΙΕΣ ΑΠΟΚΑΤΑΣΤΑΣΗΣ ΚΕΛΥΦΟΥΣ TOY ΧΑΡΑΚΤΗΡΙΣΜΕΝΟΥ ΝΕΩΤΕΡΟΥ ΜΝΗΜΕΙΟΥ ΥΠΟΣΤΕΓΟΥ Γ' ΤΗΣ ΠΟΛΕΜΙΚΗΣ ΑΕΡΟΠΟΡΙΑΣ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΡΑΣΙΝΟΥ ΚΑΙ ΑΝΑΨΥΧΗΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓ. ΚΟΣΜΑ»
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΚΑΙ ΓΕΩΦΥΣΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ ΧΕΡΣΑΙΟ ΤΜΗΜΑ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ –ΑΓ. ΚΟΣΜΑ- ΟΤ ΑΠ 1.5
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: Εκτέλεση Γεωτεχνικών και Γεωφυσικών Ερευνών, Γεωτεχνική Αξιολόγηση και Γεωτεχνικές Μελέτες Θεμελίωσης στο χερσαίο τμήμα του Μητροπολιτικού Πόλου Ελληνικού – Αγ. Κοσμά – VMT (VMC+MUT)
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΓΚΡΙΣΗ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ –
Τοποθέτηση ικριωμάτων, εκσκαφές, περίφραξη εντός των γηπέδων με αριθμούς Κ.Α.Ε.Κ.: 05050EK00205, 050412602011 και 050501801001 ευρισκόμενα ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ (ΠΡΩΗΝ ΑΝΑΤΟΛΙΚΟΣ ΑΕΡΟΛΙΜΕΝΑΣ ΕΛΛΗΝΙΚΟΥ).
Οικοδομική Άδεια (ν.4759/2020): ΝΕΟ ΚΤΙΡΙΟ ΜΕΤΕΓΚΑΤΑΣΤΑΣΗΣ ΣΥΛΛΟΓΩΝ ΑΜΕΑ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓΙΟΥ ΚΟΣΜΑ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ
Αναθεώρηση προέγκρισης Οικοδομικής Αδείας (ν.4759/2020): ΝΕΟ ΚΤΙΡΙΟ ΜΕΤΕΓΚΑΤΑΣΤΑΣΗΣ ΣΥΛΛΟΓΩΝ ΑΜΕΑ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓΙΟΥ ΚΟΣΜΑ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ
Προέγκριση για Αναθεώρηση Οικ. Αδείας (ν.4759/2020): ΕΡΓΑΣΙΕΣ ΕΣΩΤΕΡΙΚΗΣ ΔΙΑΡΡΥΘΜΙΣΗΣ ΠΡΟΣΩΡΙΝΗΣ ΑΛΛΑΓΗΣ ΧΡΗΣΗΣ ΩΣ ΚΕΝΤΡΟ ΕΝΗΜΕΡΩΣΗΣ ΚΑΙ ΕΚΘΕΣΙΑΚΟΥ ΧΩΡΟΥ ΤΟΥ ΧΑΡΑΚΤΗΡΙΣΜΕΝΟΥ ΝΕΩΤΕΡΟΥ ΜΝΗΜΕΙΟΥ ΥΠΟΣΤΕΓΟΥ Γ' ΤΗΣ ΠΟΛΕΜΙΚΗΣ ΑΕΡΟΠΟΡΙΑΣ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΡΑΣΙΝΟΥ ΚΑΙ ΑΝΑΨΥΧΗΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓ. ΚΟΣΜΑ
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΝΕΟ ΚΤΙΡΙΟ ΜΕΤΕΓΚΑΤΑΣΤΑΣΗΣ ΣΥΛΛΟΓΩΝ ΑΜΕΑ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓΙΟΥ ΚΟΣΜΑ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): ΕΡΓΑΣΙΕΣ ΕΣΩΤΕΡΙΚΗΣ ΔΙΑΡΡΥΘΜΙΣΗΣ ΠΡΟΣΩΡΙΝΗΣ ΑΛΛΑΓΗΣ ΧΡΗΣΗΣ ΩΣ ΚΕΝΤΡΟ ΕΝΗΜΕΡΩΣΗΣ ΚΑΙ ΕΚΘΕΣΙΑΚΟΥ ΧΩΡΟΥ ΤΟΥ ΧΑΡΑΚΤΗΡΙΣΜΕΝΟΥ ΝΕΩΤΕΡΟΥ ΜΝΗΜΕΙΟΥ ΥΠΟΣΤΕΓΟΥ Γ' ΤΗΣ ΠΟΛΕΜΙΚΗΣ ΑΕΡΟΠΟΡΙΑΣ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΡΑΣΙΝΟΥ ΚΑΙ ΑΝΑΨΥΧΗΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓ. ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: “ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΚΑΙ ΓΕΩΦΥΣΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ  ΜΗΤΡΟΠΟΛΙΤΙΚΟ ΠΟΛΟ ΕΛΛΗΝΙΚΟΥ – ΑΓ. ΚΟΣΜΑ
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): Νέες Αθλητικές Εγκαταστάσεις Του Μητροπολιτικού Πάρκου Πράσινου Και Αναψυχής του Μητροπολιτικού Πόλου Ελληνικού – Αγίου Κοσμά
Οικοδομική Άδεια (ν.4759/2020): Νέες Αθλητικές Εγκαταστάσεις Του Μητροπολιτικού Πάρκου Πράσινου Και Αναψυχής του Μητροπολιτικού Πόλου Ελληνικού – Αγίου Κοσμά
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: “ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΚΑΙ ΓΕΩΦΥΣΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΓΙΑ ΤΟ ΕΡΓΟ « ΠΑΡΑΧΩΡΗΣΗ ΆΔΕΙΑΣ ΛΕΙΤΟΥΡΓΙΑΣ ΕΠΙΧΕΙΡΗΣΗΣ ΚΑΖΙΝΟ(ΕΚΑΖ) ΕΥΡΕΟΣ ΦΑΣΜΑΤΟΣ ΔΡΑΣΤΗΡΙΟΤΗΤΩΝ ΣΤΟΝ ΜΗΤΡΟΠΟΛΙΤΙΚΟ ΠΟΛΟ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ» ”
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: : “ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΚΑΙ ΓΕΩΦΥΣΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΓΙΑ ΤΟ ΕΡΓΟ « ΠΑΡΑΧΩΡΗΣΗ ΆΔΕΙΑΣ ΛΕΙΤΟΥΡΓΙΑΣ ΕΠΙΧΕΙΡΗΣΗΣ ΚΑΖΙΝΟ(ΕΚΑΖ) ΕΥΡΕΟΣ ΦΑΣΜΑΤΟΣ ΔΡΑΣΤΗΡΙΟΤΗΤΩΝ ΣΤΟΝ ΜΗΤΡΟΠΟΛΙΤΙΚΟ ΠΟΛΟ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ» ”
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΚΑΤΑΣΚΕΥΗ ΕΞΩΤΕΡΙΚΗΣ ΜΕΤΑΛΛΙΚΗΣ ΡΑΜΠΑΣ, ΝΕΕΣ ΜΗΧΑΝΟΛΟΓΙΚΕΣ ΕΓΚΑΤΑΣΤΑΣΕΙΣ,
ΕΓΚΑΤΑΣΤΑΣΗ ΙΚΡΙΩΜΑΤΩΝ ΠΡΟΣ ΕΠΙΣΚΕΥΗ ΤΩΝ ΟΨΕΩΝ ΑΚΙΝΗΤΟΥ ΣΤΟ ΜΗΤΡΟΠΟΛΙΤΙΚΟ ΠΟΛΟ
ΕΛΛΗΝΙΚΟΥ ΓΙΑ ΤΗ ΣΤΕΓΑΣΗ ΚΑΙ ΛΕΙΤΟΥΡΓΙΑ ΚENTΡΟΥ ΔΗΜΙΟΥΡΓΙΚΗΣ ΑΠΑΣΧΟΛΗΣΗΣ ΚΔΑΠ- ΑΜΕΑ, ΤΟΥ ΣΥΛΛΟΓΟΥ «ΝΙΚΗ-Victor Ardant»

Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: “ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΚΑΙ ΓΕΩΦΥΣΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ ΧΕΡΣΑΙΟ ΤΜΗΜΑ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓ. ΚΟΣΜΑ- ORILINA. Yacht club and Residences. Hellinikon Marina ”
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ, ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΕΔΑΦΟΥΣ ΚΑΙ ΕΚΣΚΑΦΕΣ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.9 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΑΠ1.4
(HIGH RISE) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΑΠ1.4 (HIGH RISE) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ
 Α-Π6.11 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ, ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΕΔΑΦΟΥΣ ΚΑΙ ΕΚΣΚΑΦΕΣ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.10 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π1.6 (MAINSTREAM I) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ ΧΕΡΣΑΙΟ ΤΜΗΜΑ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓ. ΚΟΣΜΑ - HELLINIKON PARK STRUCTURES
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ 1.1.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ 1.2.2, ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ  ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.3.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.7 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.8 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ στο ΟΙΚΟΠΕΔΟ 1.3.2. ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,
ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1 ΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: AΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ  05.07.2023  ΥΠ'ΑΡΙΘΜΟΝ  737082 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ ΤΗ ΔΙΕΝΕΡΓΕΙΑ ΔΟΚΙΜΑΣΤΙΚΩΝ ΤΟΜΩΝ ΤΟΥ ΕΔΑΦΟΥΣ ΚΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ  ΣΤΟ ΟΙΚΟΠΕΔΟ ΜΕ ΚΩΔΙΚΟ 1.2.4  ΤΟΥ  ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ ΚοσμάΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΣΤΟ ΟΙΚΟΠΕΔΟ ΜΕ ΚΩΔΙΚΟ 1.2.4 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.1.5  ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: AΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 05.07.2023 ΥΠ'ΑΡΙΘΜΟΝ 737081 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ  ΤΗΝ ΔΙΕΝΕΡΓΕΙΑ ΔΟΚΙΜΑΣΤΙΚΩΝ ΤΟΜΩΝ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ  ΜΕ ΚΩΔΙΚΟ 1.2.3 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ -ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: «ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ ΧΕΡΣΑΙΟ ΤΜΗΜΑ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓ. ΚΟΣΜΑ – BELT»
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: «Γεωτεχνική μελέτη και εργασίες γεωτεχνικής έρευνας για το έργο του Ξενοδοχειακού συγκροτήματος και κατοικιών MALT στον Μητροπολιτικό Πόλο Ελληνικού - Αγίου Κοσμά»
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: «Γεωτεχνική μελέτη και εργασίες γεωτεχνικής έρευνας για το έργο του Ξενοδοχειακού συγκροτήματος και κατοικιών MALT στον Μητροπολιτικό Πόλο Ελληνικού - Αγίου Κοσμά»
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΕΣΩΤΕΡΙΚΕΣ ΔΙΑΡΡΥΘΜΙΣΕΙΣ, ΔΙΑΜΟΡΦΩΣΗ ΟΨΕΩΝ ΚΑΙ ΑΛΛΑΓΗ ΧΡΗΣΗΣ ΔΙΑΤΗΡΟΥΜΕΝΟΥ ΚΤΗΡΙΟΥ ΤΗΣ ΚΤΗΡΙΑΚΗΣ ΕΝΟΤΗΤΑΣ Β6 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΡΑΣΙΝΟΥ ΚΑΙ ΑΝΑΨΥΧΗΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓ. ΚΟΣΜΑ (ΠΡΩΗΝ ΚΤΗΡΙΟΥ ΚΑΝΟΕ-ΚΑΓΙΑΚ)
Ενημέρωση Οικοδομικής Αδείας (ν.4759/2020): ΕΝΗΜΕΡΩΣΗ ΤΗΣ ΥΠ' ΑΡΙΘΜΟΝ 414051/22 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΓΙΑ ΑΛΛΑΓΗ ΟΝΟΜΑΤΟΣ ΙΔΙΟΚΤΗΤΗ, ΠΡΟΣΘΗΚΗ ΔΥΟ ΕΞΩΤΕΡΙΚΩΝ ΚΛΙΜΑΚΩΝ ΣΥΝΤΗΡΗΣΗΣ ΔΩΜΑΤΩΝ ΚΑΙ ΠΡΟΣΘΗΚΗ Η/Μ ΦΡΕΑΤΙΟΥ ΔΕΔΔΗΕ ΣΤΟ ΥΠΟΓΕΙΟ ΓΙΑ ΤΟ ΝΕΟ ΚΤΙΡΙΟ ΜΕΤΕΓΚΑΤΑΣΤΑΣΗΣ ΣΥΛΛΟΓΩΝ ΑΜΕΑ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ στο ΟΙΚΟΠΕΔΟ 1.2.3 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 2.5.2 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.1.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ στο ΟΙΚΟΠΕΔΟ 1.1.2 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ στο ΟΙΚΟΠΕΔΟ 2.5.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.1.4  ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ -ΑΓΙΟΥ  ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.4.3 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ 2.6.2,ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ στο ΟΙΚΟΠΕΔΟ 1.2.4 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: AΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 29.05.2023 ΥΠ'ΑΡΙΘΜΟΝ 699102 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ ΤΗ ΔΙΕΝΕΡΓΕΙΑ ΔΟΚΙΜΑΣΤΙΚΩΝ ΤΟΜΩΝ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ ΜΕ ΚΩΔΙΚΟ 1.4.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ

Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 02.06.2023 ΥΠ’ΑΡΙΘΜΟΝ 705011 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ ΤΗ ΔΙΕΝΕΡΓΕΙΑ ΔΟΚΙΜΑΣΤΙΚΩΝ ΤΟΜΩΝ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚOΠΕΔΟ ΜΕ ΚΩΔΙΚΟ 1.2.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 02.06.2023 ΥΠ'ΑΡΙΘΜΟΝ 705013 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ   ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ ΜΕ ΚΩΔΙΚΟ  2.6.1.ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Ενημέρωση Οικοδομικής Αδείας (ν.4759/2020): ΕΝΗΜΕΡΩΣΗ ΤΗΣ ΥΠ' ΑΡΙΘΜΟΝ 414051/22 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΓΙΑ ΑΛΛΑΓΗ ΟΝΟΜΑΤΟΣ ΙΔΙΟΚΤΗΤΗ, ΠΡΟΣΘΗΚΗ ΔΥΟ ΕΞΩΤΕΡΙΚΩΝ ΚΛΙΜΑΚΩΝ ΣΥΝΤΗΡΗΣΗΣ ΔΩΜΑΤΩΝ ΚΑΙ ΠΡΟΣΘΗΚΗ Η/Μ ΦΡΕΑΤΙΟΥ ΔΕΔΔΗΕ ΣΤΟ ΥΠΟΓΕΙΟ ΓΙΑ ΤΟ ΝΕΟ ΚΤΙΡΙΟ ΜΕΤΕΓΚΑΤΑΣΤΑΣΗΣ ΣΥΛΛΟΓΩΝ ΑΜΕΑ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓΙΟΥ ΚΟΣΜΑ
Ενημέρωση Οικοδομικής Αδείας (ν.4759/2020): ΕΝΗΜΕΡΩΣΗ ΤΗΣ ΥΠ' ΑΡΙΘΜΟΝ 414051/22 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΓΙΑ ΑΛΛΑΓΗ ΟΝΟΜΑΤΟΣ ΙΔΙΟΚΤΗΤΗ, ΠΡΟΣΘΗΚΗ ΔΥΟ ΕΞΩΤΕΡΙΚΩΝ ΚΛΙΜΑΚΩΝ ΣΥΝΤΗΡΗΣΗΣ ΔΩΜΑΤΩΝ ΚΑΙ ΠΡΟΣΘΗΚΗ Η/Μ ΦΡΕΑΤΙΟΥ ΔΕΔΔΗΕ ΣΤΟ ΥΠΟΓΕΙΟ ΓΙΑ ΤΟ ΝΕΟ ΚΤΙΡΙΟ ΜΕΤΕΓΚΑΤΑΣΤΑΣΗΣ ΣΥΛΛΟΓΩΝ ΑΜΕΑ ΕΝΤΟΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 2.5.3 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Οικοδομική Άδεια (ν.4759/2020): COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,
ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1 ΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): Άδεια εκσκαφών και κατασκευής τοιχείων αντιστήριξης - άδεια κοπής δένδρων, στο οικόπεδο Α-Π4.17.2 του Ο.Τ. Α-Π4.17, της περιοχής προς πολεοδόμηση Α-Π4, Τομέας VI, στον Μητροπολιτικό Πόλο Ελληνικού - Αγ. Κοσμά, με σκοπό την “Ανέγερση υψηλού κτηρίου μικτής χρήσης (κατοικία, ξενοδοχείο και γραφεία) 37 ορόφων, ειδικής αρχιτεκτονικής σχεδίασης-τοπόσημο, με 3 υπόγειους ορόφους κυρίων, βοηθητικών χρήσεων και στάθμευσης, έναν ισόγειο όροφο κυρίων χρήσεων σε 2 στάθμες, 4 ορόφους γραφείων, 9 ορόφους ξενοδοχείου, 18 ορόφους κατοικιών, 2 μηχανολογικούς ορόφους και δώμα, με διαμόρφωση περιβάλλοντος χώρου (κατασκευή υδάτινων στοιχείων, περγκολών, ηχοπετασμάτων και στεγάστρων με φωτοβολταϊκά), χρήση των άρθρων 10 και 25 του ΝΟΚ όπως ισχύει”.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ στο ΟΙΚΟΠΕΔΟ 1.4.4.ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Προέγκριση για Αναθεώρηση Οικ. Αδείας (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας:  Έγκριση εργασιών δόμησης μικρής κλίμακας για την εκτέλεση εργασιών για γεωτεχνικές έρευνες σύμφωνα με τον ΕΑΚ 2003 (παρ.2.α, άρθρο 29 του Ν.4495/2017 όπως τροποποιήθηκε και ισχύει) στο οικοδομικό τετράγωνο Α-Π1.9 του Μητροπολιτικού Πόλου Ελληνικού – Αγ. Κοσμά".
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ  29.06.2023 ΥΠ'ΑΡΙΘΜΟΝ 732093 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ 1.2.2, ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ  ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας:  Έγκριση εργασιών δόμησης μικρής κλίμακας για την εκτέλεση εργασιών για γεωτεχνικές έρευνες σύμφωνα με τον ΕΑΚ 2003 (παρ.2.α, άρθρο 29 του Ν.4495/2017 όπως τροποποιήθηκε και ισχύει) στο οικοδομικό τετράγωνο Α-Π1.9 του Μητροπολιτικού Πόλου Ελληνικού – Αγ. Κοσμά".
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 02.06.2023 ΥΠ'ΑΡΙΘΜΟΝ 705009 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ ΜΕ ΚΩΔΙΚΟ 1.3.3 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Οικοδομική Άδεια (ν.4759/2020): ΕΣΩΤΕΡΙΚΕΣ ΔΙΑΡΡΥΘΜΙΣΕΙΣ, ΔΙΑΜΟΡΦΩΣΗ ΟΨΕΩΝ ΚΑΙ ΑΛΛΑΓΗ ΧΡΗΣΗΣ ΔΙΑΤΗΡΟΥΜΕΝΟΥ ΚΤΗΡΙΟΥ ΤΗΣ ΚΤΗΡΙΑΚΗΣ ΕΝΟΤΗΤΑΣ Β6 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΡΑΣΙΝΟΥ ΚΑΙ ΑΝΑΨΥΧΗΣ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ - ΑΓ. ΚΟΣΜΑ (ΠΡΩΗΝ ΚΤΗΡΙΟΥ ΚΑΝΟΕ-ΚΑΓΙΑΚ)
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΈΓΚΡΙΣΗ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΓΙΑ ΤΟΠΟΘΕΤΗΣΗ ΤΕΣΣΑΡΩΝ ΕΡΓΟΤΑΞΙΑΚΩΝ ΟΙΚΙΣΚΩΝ ΣΤΗΝ ΠΕΡΙΟΧΗ ΠΡΟΣ ΠΟΛΕΟΔΟΜΗΣΗ Α-Π2/17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: «ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ ΧΕΡΣΑΙΟ ΤΜΗΜΑ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓ. ΚΟΣΜΑ ΣΤΟ ΟΙΚΟΠΕΔΟ ΑΠ-4.16 »
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: «ΕΚΤΕΛΕΣΗ ΓΕΩΤΕΧΝΙΚΩΝ ΕΡΕΥΝΩΝ, ΓΕΩΤΕΧΝΙΚΗ ΑΞΙΟΛΟΓΗΣΗ ΚΑΙ ΓΕΩΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ ΘΕΜΕΛΙΩΣΗΣ ΣΤΟ ΧΕΡΣΑΙΟ ΤΜΗΜΑ ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓ. ΚΟΣΜΑ ΣΤΟ ΟΙΚΟΠΕΔΟ ΑΠ-4.15»
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: Έγκριση εργασιών δόμησης μικρής κλίμακας για την εκτέλεση εργασιών για γεωτεχνικές έρευνες σύμφωνα με τον ΕΑΚ 2003 (παρ.2.α, άρθρο 29 του Ν.4495/2017 όπως τροποποιήθηκε και ισχύει) στο οικοδομικό τετράγωνο Α-Π6.8 του Μητροπολιτικού Πόλου Ελληνικού – Αγ. Κοσμά".
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΕΠΕΚΑΤΑΣΗ ΤΟΥ ΧΡΟΝΟΥ ΙΣΧΥΟΣ ΚΑΙ  ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 30.06.2023 ΥΠ'ΑΡΙΘΜΟΝ 733203 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ
ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.3.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΕΠΕΚΑΤΑΣΗ ΤΟΥ ΧΡΟΝΟΥ ΙΣΧΥΟΣ ΚΑΙ  ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 30.06.2023 ΥΠ'ΑΡΙΘΜΟΝ 733203 ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ
ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.3.1 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ.
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας: ΕΠΕΚΤΑΣΗ ΤΟΥ ΧΡΟΝΟΥ ΙΣΧΥΟΣ  ΚΑΙ  ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ ΑΠΟ 24.07.2023 ΥΠ’ΑΡΙΘΜΟΝ  756254  ΠΡΑΞΗΣ ΕΓΚΡΙΣΗΣ ΕΡΓΑΣΙΩΝ ΔΟΜΗΣΗΣ ΜΙΚΡΗΣ ΚΛΙΜΑΚΑΣ ΜΕ ΘΕΜΑ " ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΤΟΥ ΕΔΑΦΟΥΣ ΚΑΙ ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ 2.6.2,ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ"

In [9]:
pd.DataFrame(filtered_results).to_csv("oikodomikes_adeies.csv", index=False)

In [10]:
filtered_results = []
for item in results:
    for t in terms:
        if t in item['subject']:
            print(item['subject'])

            filtered_results.append(item)
r = pd.DataFrame(filtered_results)

Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 4 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 18 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ , ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ , ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΚΑΙ ΧΡΗΣΗ ΤΟΥ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.6Β
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ, ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΕΔΑΦΟΥΣ ΚΑΙ ΕΚΣΚΑΦΕΣ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.9 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ
 Α-Π6.11 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ, ΔΟΚΙΜΑΣΤΙΚΕΣ ΤΟΜΕΣ ΕΔΑΦΟΥΣ ΚΑΙ ΕΚΣΚΑΦΕΣ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.10 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ
ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π1.6 (MAINSTREAM I) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.7 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΓΙΑ ΓΕΩΤΕΧΝΙΚΗ ΕΡΕΥΝΑ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.8 (MAINSTREAM II) ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ – ΑΓΙΟΥ ΚΟΣΜΑ
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 5 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 14 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΚΑΙ ΧΡΗΣΗ ΤΟΥ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.8
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 9 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ,ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ,ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ,30 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒ.ΧΩΡΟΥ,ΑΔΕΙΑ  ΚΟΠΗΣ ΔΕΝΔΡΩΝ ΚΑΙ  ΧΡΗΣΗ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ  ΟΠΩΣ ΙΣΧΥΕΙ ,
ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.7Β
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,
ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1 ΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 5 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 14 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΚΑΙ ΧΡΗΣΗ ΤΟΥ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.8
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 5 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 14 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΚΑΙ ΧΡΗΣΗ ΤΟΥ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.8
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 9 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ,ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ,ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ,30 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒ.ΧΩΡΟΥ,ΑΔΕΙΑ  ΚΟΠΗΣ ΔΕΝΔΡΩΝ ΚΑΙ  ΧΡΗΣΗ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ  ΟΠΩΣ ΙΣΧΥΕΙ ,
ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.7Β
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 9 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ,ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ,ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ,30 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒ.ΧΩΡΟΥ,ΑΔΕΙΑ  ΚΟΠΗΣ ΔΕΝΔΡΩΝ ΚΑΙ  ΧΡΗΣΗ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ  ΟΠΩΣ ΙΣΧΥΕΙ ,
ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.7Β
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 4 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 18 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ , ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ , ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΚΑΙ ΧΡΗΣΗ ΤΟΥ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.6Β
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ 3 ΤΡΙΩΡΟΦΩΝ ΚΤΗΡΙΩΝ ΚΑΤΟΙΚΙΩΝ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 14 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΚΑΙ ΧΡΗΣΗ ΤΟΥ ΑΡΘΡΟΥ 25 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ ΠΜ-Π1.5Β
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΕΝΑ ΒΟΗΘΗΤΙΚΟ ΚΤΙΡΙΟ, ΔΥΟ ΑΝΟΙΧΤΕΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΔΥΟ ΥΔΑΤΙΝΕΣ ΕΠΙΦΑΝΕΙΕΣ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.4.2)
ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.4
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Οικοδομική Άδεια (ν.4759/2020): COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,
ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1 ΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): Άδεια εκσκαφών και κατασκευής τοιχείων αντιστήριξης - άδεια κοπής δένδρων, στο οικόπεδο Α-Π4.17.2 του Ο.Τ. Α-Π4.17, της περιοχής προς πολεοδόμηση Α-Π4, Τομέας VI, στον Μητροπολιτικό Πόλο Ελληνικού - Αγ. Κοσμά, με σκοπό την “Ανέγερση υψηλού κτηρίου μικτής χρήσης (κατοικία, ξενοδοχείο και γραφεία) 37 ορόφων, ειδικής αρχιτεκτονικής σχεδίασης-τοπόσημο, με 3 υπόγειους ορόφους κυρίων, βοηθητικών χρήσεων και στάθμευσης, έναν ισόγειο όροφο κυρίων χρήσεων σε 2 στάθμες, 4 ορόφους γραφείων, 9 ορόφους ξενοδοχείου, 18 ορόφους κατοικιών, 2 μηχανολογικούς ορόφους και δώμα, με διαμόρφωση περιβάλλοντος χώρου (κατασκευή υδάτινων στοιχείων, περγκολών, ηχοπετασμάτων και στεγάστρων με φωτοβολταϊκά), χρήση των άρθρων 10 και 25 του ΝΟΚ όπως ισχύει”.
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ TPΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΔΩΜΑ, ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ (2.7.4) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.7Α
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΔΥΟ ΑΣΚΕΠΕΙΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ ΚΑΙ ΔΥΟ ΥΔΑΤΙΝΕΣ ΕΠΙΦΑΝΕΙΕΣ ΣΤΟΝ ΠΕΡΙΒΑΛΛΟΝΤΑ ΧΩΡΟ, ΜΙΑ ΕΣΩΤΕΡΙΚΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ ΣΤΟ ΥΠΟΓΕΙΟ, ΧΩΡΟ ΚΥΡΙΑΣ ΧΡΗΣΗΣ ΣΤΟ ΔΩΜΑ ΤΟΥ ΚΤΙΡΙΟΥ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΣΤΟ ΟΙΚΟΠΕΔΟ (2.7.5) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.7Α
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΤΡΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΠΕΔΟ (2.7.3) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.7Α
Προέγκριση για Αναθεώρηση Οικ. Αδείας (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ TPΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΔΩΜΑ, ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ (2.7.4) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.7Α
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΔΥΟ ΑΣΚΕΠΕΙΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ ΚΑΙ ΔΥΟ ΥΔΑΤΙΝΕΣ ΕΠΙΦΑΝΕΙΕΣ ΣΤΟΝ ΠΕΡΙΒΑΛΛΟΝΤΑ ΧΩΡΟ, ΜΙΑ ΕΣΩΤΕΡΙΚΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ ΣΤΟ ΥΠΟΓΕΙΟ, ΧΩΡΟ ΚΥΡΙΑΣ ΧΡΗΣΗΣ ΣΤΟ ΔΩΜΑ ΤΟΥ ΚΤΙΡΙΟΥ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΣΤΟ ΟΙΚΟΠΕΔΟ (2.7.5) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.7Α
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ (1.2.3) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020): COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΚΟΠΗ ΔΕΝΔΡΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ (1.2.3) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2
Οικοδομική Άδεια (ν.4759/2020): ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΔΥΟ ΣΥΓΚΡΟΤΗΜΑΤΩΝ ΚΑΤΟΙΚΙΩΝ ΑΠΟΤΕΛΟΥΜΕΝΩΝ ΑΠΟ ΠΕΝΤΕ ΠΕΝΤΑΩΡΟΦΑ ΚΤΙΡΙΑ ΚΑΤΟΙΚΙΩΝ ΚΑΙ ΔΥΟ ΠΕΝΤΑΩΡΟΦΑ ΚΤΙΡΙΑ ΚΑΤΟΙΚΙΩΝ ΜΕ ΤΜΗΜΑ ΑΠΟ ΙΣΟΓΕΙΑ ΕΜΠΟΡΙΚΑ ΚΑΤΑΣΤΗΜΑΤΑ ΜΕ ΠΑΤΑΡΙ, ΜΕ ΥΠΟΓΕΙΟ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ ΚΑΙ ΧΩΡΩΝ ΣΤΑΘΜΕΥΣΗΣ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΣΤΟ Ο.Τ. Α-Π6.11
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΑΝΟΙΧΤΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ , ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.1.1 ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.1
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ
ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΔΥΟ ΑΝΟΙΧΤΕΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΔΙΑΜΟΡΦΩΣΗ
ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.2.4) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ
ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΔΥΟ ΑΝΟΙΧΤΕΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ, ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.4.1 ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.4
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΕΞΩΤ. ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΠΕΔΟ (1.1.2) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.1
Οικοδομική Άδεια (ν.4759/2020): ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΝΕΟΥ ΣΥΓΚΡΟΤΗΜΑΤΟΣ ΤΡΙΩΝ ΠΕΝΤΑΩΡΟΦΩΝ ΚΤΙΡΙΩΝ ΚΑΤΟΙΚΙΩΝ ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΧΡΗΣΗ ΤΟΥ AΡΘΡΟΥ 10 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ, ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.10
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΤΡΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΑΝΟΙΧΤΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ , ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 2.6.1 ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.6Α
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΕΝΑ ΒΟΗΘΗΤΙΚΟ ΚΤΙΡΙΟ, ΔΥΟ ΑΝΟΙΧΤΕΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΔΥΟ ΥΔΑΤΙΝΕΣ ΕΠΙΦΑΝΕΙΕΣ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.4.2)
ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.4
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ
ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΔΥΟ ΑΝΟΙΧΤΕΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΔΙΑΜΟΡΦΩΣΗ
ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.2.4) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ
ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΔΥΟ ΑΝΟΙΧΤΕΣ ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ, ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.4.1 ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.4
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΤΡΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΑΝΟΙΧΤΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ , ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 2.6.1 ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.6Α
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΕΞΩΤ. ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΠΕΔΟ (1.1.2) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.1
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΕΞΩΤ. ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΠΕΔΟ (1.1.2) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.1
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΑΝΟΙΧΤΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ , ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.1.1 ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.1
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΝΕΟΥ ΣΥΓΚΡΟΤΗΜΑΤΟΣ ΔΥΟ ΠΕΝΤΑΩΡΟΦΩΝ ΚΤΙΡΙΩΝ ΚΑΤΟΙΚΙΩΝ ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ ΚΑΙ ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.9
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΝΕΟΥ ΣΥΓΚΡΟΤΗΜΑΤΟΣ ΤΡΙΩΝ ΠΕΝΤΑΩΡΟΦΩΝ ΚΤΙΡΙΩΝ ΚΑΤΟΙΚΙΩΝ ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΧΡΗΣΗ ΤΟΥ AΡΘΡΟΥ 10 ΤΟΥ ΝΟΚ ΟΠΩΣ ΙΣΧΥΕΙ, ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.10
Οικοδομική Άδεια (ν.4759/2020): ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΝΕΟΥ ΣΥΓΚΡΟΤΗΜΑΤΟΣ ΔΥΟ ΠΕΝΤΑΩΡΟΦΩΝ ΚΤΙΡΙΩΝ ΚΑΤΟΙΚΙΩΝ ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ ΚΑΙ ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π6.9
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΔΥΟ ΣΥΓΚΡΟΤΗΜΑΤΩΝ ΚΑΤΟΙΚΙΩΝ ΑΠΟΤΕΛΟΥΜΕΝΩΝ ΑΠΟ ΠΕΝΤΕ ΠΕΝΤΑΩΡΟΦΑ ΚΤΙΡΙΑ ΚΑΤΟΙΚΙΩΝ ΚΑΙ ΔΥΟ ΠΕΝΤΑΩΡΟΦΑ ΚΤΙΡΙΑ ΚΑΤΟΙΚΙΩΝ ΜΕ ΤΜΗΜΑ ΑΠΟ ΙΣΟΓΕΙΑ ΕΜΠΟΡΙΚΑ ΚΑΤΑΣΤΗΜΑΤΑ ΜΕ ΠΑΤΑΡΙ, ΜΕ ΥΠΟΓΕΙΟ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ ΚΑΙ ΧΩΡΩΝ ΣΤΑΘΜΕΥΣΗΣ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΣΤΟ Ο.Τ. Α-Π6.11
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΜΙΑ ΑΝΟΙΧΤΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ,
ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.2.1
ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΔΙΩΡΟΦΗΣ ΜΟΝΟΚΑΤΟΙΚΙΑΣ, ΜΕ ΕΝΑΝ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ, ΠΑΤΑΡΙ, ΦΥΤΕΜΕΝΟ ΔΩΜΑ, ΜΙΑ ΑΝΟΙΧΤΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ,
ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ 1.2.1
ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας:  Έγκριση εργασιών δόμησης μικρής κλίμακας για την εκτέλεση εργασιών για γεωτεχνικές έρευνες σύμφωνα με τον ΕΑΚ 2003 (παρ.2.α, άρθρο 29 του Ν.4495/2017 όπως τροποποιήθηκε και ισχύει) στο οικοδομικό τετράγωνο Α-Π1.9 του Μητροπολιτικού Πόλου Ελληνικού – Αγ. Κοσμά".
Αναθεώρηση Έγκρισης Εργασιών Δόμησης Μικρής Κλίμακας:  Έγκριση εργασιών δόμησης μικρής κλίμακας για την εκτέλεση εργασιών για γεωτεχνικές έρευνες σύμφωνα με τον ΕΑΚ 2003 (παρ.2.α, άρθρο 29 του Ν.4495/2017 όπως τροποποιήθηκε και ισχύει) στο οικοδομικό τετράγωνο Α-Π1.9 του Μητροπολιτικού Πόλου Ελληνικού – Αγ. Κοσμά".
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΠΕΝΕΤΡΟΜΕΤΡΗΣΕΩΝ ΓΙΑ ΤΗΝ ΕΚΠΟΝΗΣΗ ΓΕΩΤΕΧΝΙΚΗΣ ΕΡΕΥΝΑΣ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.3.1) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.3.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΠΕΝΕΤΡΟΜΕΤΡΗΣΕΩΝ ΓΙΑ ΤΗΝ ΕΚΠΟΝΗΣΗ ΓΕΩΤΕΧΝΙΚΗΣ ΕΡΕΥΝΑΣ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.3.2) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.3.
Έγκριση Εργασιών Δόμησης Μικρής Κλίμακας: ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΠΕΝΕΤΡΟΜΕΤΡΗΣΕΩΝ ΓΙΑ ΤΗΝ ΕΚΠΟΝΗΣΗ ΓΕΩΤΕΧΝΙΚΗΣ ΕΡΕΥΝΑΣ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.3.3) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.3.
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΣΥΓΚΡΟΤΗΜΑΤΟΣ ΠΟΥ ΑΠΟΤΕΛΕΙΤΑΙ ΑΠΟ 4 ΕΞΑΩΡΟΦΑ ΚΤΙΡΙΑ ΜΙΚΤΗΣ ΧΡΗΣΗΣ, ΜΕ ΧΡΗΣΕΙΣ ΕΜΠΟΡΙΟΥ & ΕΣΤΙΑΣΗΣ ΣΤΟ ΙΣΟΓΕΙΟ ΚΑΙ ΧΡΗΣΗ ΚΑΤΟΙΚΙΑΣ ΣΤΟΥΣ ΟΡΟΦΟΥΣ ΚΑΙ 3 ΕΞΑΩΡΟΦΑ ΚΤΙΡΙΑ ΜΕ ΧΡΗΣΗ ΚΑΤΟΙΚΙΑΣ, ΜΕ ΠΡΩΤΟ ΥΠΟΓΕΙΟ ΟΡΟΦΟ ΣΤΑΘΜΕΥΣΗΣ, ΒΟΗΘΗΤΙΚΩΝ ΚΑΙ ΚΥΡΙΩΝ ΧΩΡΩΝ ΚΑΙ ΤΜΗΜΑ ΔΕΥΤΕΡΟΥ ΥΠΟΓΕΙΟΥ ΟΡΟΦΟΥ ΣΤΑΘΜΕΥΣΗΣ KAI ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΕΣΩΤΕΡΙΚΟΥΣ ΕΞΩΣΤΕΣ, ΦΥΤΕΜΕΝΑ ΔΩΜΑΤΑ, 7 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ ΣΤΑ ΔΩΜΑΤΑ, 4 ΚΟΛΥΜΒΗΤΙΚΕΣ ΔΕΞΑΜΕΝΕΣ ΚΑΙ ΔΥΟ ΥΔΑΤΙΝΑ ΣΤΟΙΧΕΙΑ ΣΤΟΝ ΑΚΑΛΥΠΤΟ ΧΩΡΟ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΑΔΕΙΑ ΚΟΠΗΣ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ Α-Π1.6
Οικοδομική Άδεια (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΤΡΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ ΚΑΙ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΣΤΟ ΟΙΚΟΠΕΔΟ (2.7.3) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.7Α
Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΦΥΛΑΚΙΟ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.1.5) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.1

Προέγκριση Οικοδομικής Αδείας (ν.4759/2020): ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ ΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΕΞΩΤΕΡΙΚΗ ΚΟΛΥΜΒΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ ΚΑΙ ΚΟΠΗ ΠΕΝΤΕ ΔΕΝΤΡΩΝ ΣΤΟ ΟΙΚΟΠΕΔΟ (1.4.3) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.4

In [11]:
r.to_csv("oikopeda.csv", index = False)

In [12]:
pd.DataFrame(results).to_csv("ellhniko_all.csv", index=False)

In [13]:
from IPython.display import clear_output

In [14]:
import os
import glob
import pdfplumber

In [15]:
pdfs = glob.glob("/Users/troboukis/Code/lambda/documents/oik_adeies/*")
print(f"Έχουμε {len(pdfs)} pdf")

Έχουμε 153 pdf

In [16]:
save_path = "/Users/troboukis/Code/lambda/documents/oik_adeies/{}.pdf"
docName = [re.search(r"adeies/(.*).pdf", i).group(1) for i in pdfs]
c = 0
for i in filtered_results:
    c+=1
    try:
        if re.search("doc/(.*)", i['documentUrl']).group(1) not in docName:
            response = requests.get(i['documentUrl'])
            print(f"Getting: {c}/{len(filtered_results)}")
            with open(save_path.format(i['ada']), "wb") as f:
                        f.write(response.content)
            with open("download_report.log", "a", encoding="utf-8") as log:
                log.write(f"[{datetime.now().isoformat()}] ADA {i['ada']} downloaded successfully\n")

            time.sleep(1)
            clear_output(wait=True)
    except Exception as e:
        print (e)
        with open("download_report.log", "a", encoding="utf-8") as log:
            log.write(f"[{datetime.now().isoformat()}] ADA {i['ada']} NOT DOWNLOADED\n")
        clear_output(wait=True)

Getting: 157/157

In [17]:
import os
import glob
import pdfplumber
from itertools import chain

pdfs = glob.glob("/Users/troboukis/Code/lambda/documents/oik_adeies/*")
print(f"Έχουμε {len(pdfs)} pdf")

all_parsed = []
counter = 0
total = len(pdfs)
for document in pdfs:
    result = {}
    counter+=1
    ada = os.path.basename(document)
    print(f"{counter}/{total}")
    print(f'parsing: {ada}')
    with pdfplumber.open(document) as pdf:
        parsed = []
        for page in pdf.pages:
            tables = page.extract_tables()
            for table in tables:
                # if any("ΜΕΤΛΕΝ" in (cell or "") for cell in chain.from_iterable(table)):
                #     print(table[0])
                print(table)
                parsed.append(table)
        print("------")
    all_parsed.append(parsed)

Έχουμε 157 pdf
1/157
parsing: 9Γ0Ξ46Ψ842-Γ7Ω.pdf
[['Α/Α Πράξης', '1512911'], ['Ημ/νία έκδοσης πράξης', '09/07/2025'], ['Ισχύει έως', '09/07/2029']]
[['Στοιχεία έργου', None], ['Περιγραφή\nΈργου/Εγκατάστασης', 'ΑΝΕΓΕΡΣΗ ΥΠΟΓΕΙΟΥ ΥΠΟΣΤΑΘΜΟΥ ΜΕΣΗΣ ΤΑΣΗΣ (20kV) ΔΕΔΔΗΕ ΔΙΑΝΟΜΗΣ\nΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ στο ΟΤ Α-Π4.10'], ['Οδός', 'O.T. Α-Π4.10 ΠΕΡΙΟΧΗΣ Α-Π4, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΓ.ΚΟΣΜΑ'], ['Αρ. από', '-'], ['Αρ. έως', ''], ['Πόλη/Οικισμός', 'ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ. ΚΟΣΜΑ'], ['Δήμος', 'Ελληνικού-Αργυρούπολης'], ['Δημοτική Ενότητα /\nΠεριοχή', 'Περιοχή προς Πολεοδόμηση Α-Π4 - Tομέας VΙΙI "Γειτονιά Επιχειρηματικού Κέντρου\nΛεωφόρου Βουλιαγμένης" του Μ.Π. Ελληνικού-Αγ.Κοσμά'], ['ΟΤ', 'Α-Π4.10'], ['ΚΑΕΚ', '050501505002/0/0επιφ'], ['Ηλ. κλειδί πράξης', '7C700C51C441DE6B'], ['Τύπος Πράξης', 'Οικοδομική Άδεια (ν.4759/2020)'], ['A/A Αίτησης', '2014682'], ['Διαχειριστής Αίτησης', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]']]
[['Στοιχεία κυρίου του έργου', None, None, None, None, None], ['Επώνυμο/ία', 'Όνομα', 'Όνομα πατέρα', 'Ιδιότητα', 'Ποσοστό', 'Τύπος\nδικαιώματος'], ['ΕΛΛΗΝΙΚΟ Μ.Α.Ε.', '-', '', 'Ιδιοκτήτης', '0', 'Πλήρης\nκυριότητα'], ['ΝΤΕΓΙΑΝΝΗΣ', 'ΗΛΙΑΣ', 'ΣΩΤΗΡΙΟΣ', 'Εξουσιοδοτημέν\nο\nπρόσωπο/Νόμιμο\nς Εκπρόσωπος', '0', '-'], ['ΕΛΛΗΝΙΚΟ Μ.Α.Ε.', '-', '', 'Επιφανειούχος\n(Ν. 3986/2011)', '100', 'Επιφάνεια']]
[['Προέγκριση Οικοδομικής Αδείας (ν.4759/2020)', None], ['Α/Α Πράξης', '1502152'], ['A/A Αίτησης', '1962279'], ['Περιγραφή έργου', 'ΑΝΕΓΕΡΣΗ ΥΠΟΓΕΙΟΥ ΥΠΟΣΤΑΘΜΟΥ ΜΕΣΗΣ ΤΑΣΗΣ (20kV) ΔΕΔΔΗΕ ΔΙΑΝΟΜΗΣ\nΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ στο ΟΤ Α-Π4.10'], ['Ημ/νία έκδοσης πράξης', '02/07/2025'], ['Ισχύει έως', '02/07/2028'], ['Ηλ. κλειδί αίτησης', '0DC7D60328BFF360'], ['ΑΔΑ', '98Η246Ψ842-Ο5Ξ']]
[['Εγκρίσεις Φορέων', None, None, None], ['Τύπος Έγκρισης', 'Αρμόδια Υπηρεσία', 'Αρ. Πρωτ.', 'Ημ/νία'], ['Έγκριση\nΚΕ.Σ.Α./ΚΕ.Σ.Α.Α./ΚΕ.Σ.\nΑ.ΜΑ.Θ.', 'ΚΕΝΤΡΙΚΟ ΣΥΜΒΟΥΛΙΟ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ', '1491292', '24/06/2025'], ['Υποσταθμός ρεύματος', 'ΔΕΔΔΗΕ', '195082', '05/06/2025'], ['Έγκριση Υψομέτρου', 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ & ΕΝΕΡΓΕΙΑΣ ΓΕΝΙΚΗ\nΓΡΑΜΜΑΤΕΙΑ ΧΩΡΙΚΟΥ ΣΧΕΔΙΑΣΜΟΥ ΚΑΙ ΑΣΤΙΚΟΥ\nΠΕΡΙΒΑΛΛΟΝΤΟΣ ΓΡΑΦΕΙΟ ΕΛΛΗΝΙΚΟΥ', '61596/328', '04/06/2025']]
[['Στοιχεία Διαγράμματος Κάλυψης', None, None, None, None], ['Εμβαδόν οικοπέδου', '11.106,468', None, None, None], ['', 'ΥΦΙΣΤΑΜΕΝΑ', 'ΝΟΜΙΜΟΠΟΙΟΥ\nΜΕΝΑ', 'ΠΡΑΓΜΑΤΟΠΟΙΟ\nΥΜΕΝΑ', 'ΣΥΝΟΛΟ'], ['Εμβ. κάλυψης κτιρίου', '0', '0', '0', '0'], ['Εμβ. δόμησης κτιρίου', '0', '0', '0', '0'], ['Εμβ. ακάλυπτου χώρου οικοπέδου', '0', '0', '0', '0'], ['Όγκος κτιρίου (άνω εδάφους)', '0', '0', '0', '0'], ['Μέγιστο ύψος κτιρίου', '0', '0', '0', '0'], ['Αριθμός Ορόφων', '0', '0', '0', '0'], ['Αριθμός Θέσεων Στάθμευσης', '0', '0', '0', '0'], ['Χρήσεις ανά όροφο', '1ο υπόγειο', None, 'Λοιπές Χρήσεις', None]]
[['ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ', None], ['Μελέτη τοπογραφικού\nδιαγράμματος', 'ΜΑΤΘΑΙΟΥ ΑΓΓΕΛΟΣ (A.M. TEE:84102), ΑΓΡΟΝΟΜΟΣ ΤΟΠΟΓΡΑΦΟΣ ΜΗΧΑΝΙΚΟΣ[2000]'], ['Διάγραμμα Κάλυψης\nΑρχιτεκτονικής Μελέτης', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Αρχιτεκτονική μελέτη', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Στατική μελέτη', 'ΚΟΝΤΙΖΑΣ ΑΘΑΝΑΣΙΟΣ (A.M. TEE:56467), ΠΟΛΙΤΙΚΟΣ ΜΗΧΑΝΙΚΟΣ[1990]'], ['Μελέτη ηλεκτρικών\nεγκαταστάσεων', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ['Μελέτη χρονικού\nπρογραμματισμού', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Μελέτη ενεργητικής\nπυροπροστασίας', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ['Μελέτη παθητικής\nπυροπροστασίας', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]']]
[['ΟΜΑΔΑ ΕΠΙΒΛΕΨΗΣ ΕΡΓΟΥ', None], ['Επίβλεψη Αρχιτεκτονικής\nμελέτης (Γενική επίβλεψη)', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Επίβλεψη στατικής\nμελέτης', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Επίβλεψη ηλεκτρικών\nεγκαταστάσεων', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ['Επίβλεψη εγκατάστασης\nπυροπροστασίας', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ["Συντονισμός μέτρων\nασφαλείας & υγείας κατά\nτα οριζόμενα στο ΠΔ\n305/1996 (Α'212)", 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Εφαρμογή χρονικού\nπρογραμματισμού', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]']]
[['ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ', None], ['Συντεταγμένες', '477244.65011430014 4194368.597070529,477255.23346880014 4194262.102065873,477152.707222081\n4194251.5187113727,477141.4624079247 4194357.352256373'], ['', None]]
------
2/157
parsing: 6ΥΩ246Ψ842-16Μ.pdf
[['Α/Α Πράξης', '1143553'], ['Ημ/νία έκδοσης πράξης', '02/08/2024'], ['Ισχύει έως', '02/08/2027']]
[['Στοιχεία έργου', None], ['Περιγραφή\nΈργου/Εγκατάστασης', 'ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ\nΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ,\nΔΙΑΚΟΣΜΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ ΚΑΙ ΚΟΠΗ\nΕΝΟΣ ΔΕΝΤΡΟΥ, ΣΤO ΟΙΚΟΠΕΔΟ (1.2.2) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2'], ['Οδός', 'O.T.ΠΜ-Π1.2 ΠΕΡΙΟΧΗΣ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ.ΚΟΣΜΑ'], ['Αρ. από', '0'], ['Αρ. έως', '0'], ['Πόλη/Οικισμός', 'ΑΛΙΜΟΣ'], ['Δήμος', 'Αλίμου'], ['Δημοτική Ενότητα /\nΠεριοχή', 'ΠΕΡΙΟΧΗ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ.ΚΟΣΜΑ'], ['ΟΤ', 'ΠΜ-Π1.2'], ['ΚΑΕΚ', '050134706003/0/0'], ['Ηλ. κλειδί πράξης', 'C74E4BD8D7038383'], ['Τύπος Πράξης', 'Προέγκριση Οικοδομικής Αδείας (ν.4759/2020)'], ['A/A Αίτησης', '1496596'], ['Διαχειριστής Αίτησης', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ']]
[['Στοιχεία κυρίου του έργου', None, None, None, None, None], ['Επώνυμο/ία', 'Όνομα', 'Όνομα πατέρα', 'Ιδιότητα', 'Ποσοστό', 'Τύπος\nδικαιώματος'], ['SUNSET COVE M.A.E', 'SUNSET COVE\nM.A.E', '', 'Ιδιοκτήτης', '100', 'Πλήρης\nκυριότητα'], ['ΤΟΥΖΙΟΥ (ΕΛΛΗΝΙΚΟ ΜΑΕ)', 'ΑΓΓΕΛΙΚΗ', 'ΔΗΜΗΤΡΙΟΣ', 'Εξουσιοδοτημέν\nο\nπρόσωπο/Νόμιμο\nς Εκπρόσωπος', '0', '-']]
[['Πρόσθετες Επιλογές'], ['Ισχύς Αδείας 4 έτη (Ανέγερση κτιρίων <5000τμ & Λοιπ.Περιπτώσεις)']]
[['Στοιχεία Διαγράμματος Κάλυψης', None, None, None, None], ['Εμβαδόν οικοπέδου', '2.094,011', None, None, None], ['', 'ΥΦΙΣΤΑΜΕΝΑ', 'ΝΟΜΙΜΟΠΟΙΟΥ\nΜΕΝΑ', 'ΠΡΑΓΜΑΤΟΠΟΙΟ\nΥΜΕΝΑ', 'ΣΥΝΟΛΟ']]
[['Εμβ. κάλυψης κτιρίου', '0', '0', '575,84', '575,84'], ['Εμβ. δόμησης κτιρίου', '0', '0', '732,54', '732,54'], ['Εμβ. ακάλυπτου χώρου οικοπέδου', '0', '0', '1.518,17', '1.518,17'], ['Όγκος κτιρίου (άνω εδάφους)', '0', '0', '3.412,11', '3.412,11'], ['Μέγιστο ύψος κτιρίου', '0', '0', '7,8', '7,8'], ['Αριθμός Ορόφων', '0', '0', '2', '2'], ['Αριθμός Θέσεων Στάθμευσης', '0', '0', '10', '10'], ['Χρήσεις ανά όροφο', '1ο υπόγειο', None, 'Κατοικίες', None], [None, None, None, 'Βοηθητική Χρήση', None], [None, 'Ισόγειο', None, 'Κατοικίες', None], [None, '1ος όροφος', None, 'Κατοικίες', None]]
[['ΑΠΑΙΤΟΥΜΕΝΕΣ ΕΓΚΡΙΣΕΙΣ', None], ['', 'Έγκριση Σ.Α. / Σ.Α. Αιγαίου'], ['X', 'Έγκριση Κ.Ε.Σ.Α./Κ.Ε.Σ.Α.Α./ΚΕ.Σ.Α.ΜΑ.Θ./ΚΕ.Σ.Ε.Α.'], ['', 'Έγκριση ΣΥ.ΠΟ.Θ.Α. / KΕ.ΣΥ.ΠΟ.Θ.Α.'], ['', 'Έγκριση Δασικής Υπηρεσίας'], ['X', 'Έγκριση Εφορείας Προϊστορικών & Κλασικών Αρχαιοτήτων'], ['', 'Έγκριση Εφορείας Βυζαντινών Αρχαιοτήτων'], ['', 'Έγκριση Εφορείας Νεωτέρων Μνημείων'], ['', 'Έγκριση Εφορείας Αρχαιοτήτων'], ['', 'Έγκριση οριοθέτησης υδατορέματος'], ['', 'Έγκριση Υπηρεσίας Πολιτ. Αεροπορίας'], ['', 'Άλλες εγκρίσεις'], ['', 'Έγκριση ΠΕ.ΣΥ.ΠΟ.Θ.Α.'], ['', 'Έγκριση ΝΕΧΩΠ για γη υψηλής παραγωγικότητας'], ['', 'Έγκριση Κυκλοφοριακής σύνδεσης'], ['', 'Έγκριση αρμόδιου φορέα'], ['', 'Έγκριση ΔΕΗ για απόσταση από καλώδια Υψηλής Τάσης'], ['X', 'Έγκριση Υψομέτρου'], ['', 'Έγκριση Οριοθέτησης Αιγιαλού'], ['', 'Πρωτόκολλο αδυνάτου τακτοποίησης(§3α αρθ.36-όμορα μη οικοδομ.)'], ['', 'Κύρωση δικτύου κοινοχρήστων χώρων(§3γ αρθ.36-δίκτυο μη κυρωμένο)']]
[['ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ', None], ['Μελέτη τοπογραφικού\nδιαγράμματος', 'Σ. ΚΑΤΣΩΛΗΣ - Δ. ΜΠΙΛΑΛΗΣ Ο.Ε. δ.τ. XYZ ΤΟΠΟΓΡΑΦΙΚΕΣ ΜΕΛΕΤΕΣ (Αρ. ΤΕΕ:25260),\nΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΚΑΤΣΩΛΗΣ ΣΤΕΦΑΝΟΣ (A.M. TEE:66661), ΑΓΡΟΝΟΜΟΣ ΤΟΠΟΓΡΑΦΟΣ ΜΗΧΑΝΙΚΟΣ[1993]'], ['Διάγραμμα Κάλυψης\nΑρχιτεκτονικής Μελέτης', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Αρχιτεκτονική μελέτη', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Μελέτη χρονικού\nπρογραμματισμού', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Μελέτη παθητικής\nπυροπροστασίας', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Λοιπές Εργασίες - Μελέτες', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]']]
[['Ομάδα Ελέγχου Έργου', None], ["Τοπογραφικό διάγραμμα Ε.Γ.Σ.Α. '87", 'ΠΑΠΑΣΠΥΡΟΥ ΠΕΤΡΟΣ'], ['Διάγραμμα κάλυψης Αρχιτεκτονικής\nΜελέτης', 'ΤΣΙΤΣΟΥΛΑΣ-ΓΙΑΓΚΟΥΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ']]
------
3/157
parsing: ΨΣΖΞ46Ψ842-86Ω.pdf
[['Α/Α Πράξης', '878905'], ['Ημ/νία έκδοσης πράξης', '30/11/2023'], ['Ισχύει έως', '14/07/2024']]
[['Στοιχεία έργου', None], ['Περιγραφή\nΈργου/Εγκατάστασης', 'COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ\nΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ\nΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ\nΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ\nΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ\nΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,\nΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-Π4.17.1 TOY\nΟ.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ'], ['Οδός', 'ΠΕΡΙΟΧΗ ΠΡΟΣ ΠΟΛΕΟΔΟΜHΣΗ Α-Π4,ΤΟΜΕΑΣ VI'], ['Αρ. από', '-'], ['Αρ. έως', ''], ['Πόλη/Οικισμός', 'ΕΛΛΗΝΙΚΟ'], ['Δήμος', 'Ελληνικού-Αργυρούπολης'], ['Δημοτική Ενότητα /\nΠεριοχή', 'ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΓ.ΚΟΣΜΑ'], ['ΟΤ', 'Α-Π4.17'], ['ΚΑΕΚ', '050501528002'], ['Ηλ. κλειδί πράξης', 'B418CD3207080E65'], ['Τύπος Πράξης', 'Αναθεώρηση Οικ. Αδείας ME προέγκριση ή βεβαίωση (ν.4759/2020)'], ['A/A Αίτησης', '1241893'], ['Διαχειριστής Αίτησης', 'Α & Μ ARCHITECTS Α.Ε. δ.τ. Α & Μ ARCHITECTS (Αρ. ΤΕΕ:1382), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ']]
[['Στοιχεία κυρίου του έργου', None, None, None, None, None], ['Επώνυμο/ία', 'Όνομα', 'Όνομα πατέρα', 'Ιδιότητα', 'Ποσοστό', 'Τύπος\nδικαιώματος'], ['ΕΛΛΗΝΙΚΟ Μ.Α.Ε.', '-', '-', 'Ιδιοκτήτης', '16', 'Πλήρης\nκυριότητα'], ['LAMDA VOULIAGMENIS S.M.S.A.', '-', '-', 'Ιδιοκτήτης', '84', 'Πλήρης\nκυριότητα'], ['ΠΑΙΖΗ', 'ΜΕΛΙΝΑ-\nΣΩΤΗΡΙΑ', 'ΓΕΩΡΓΙΟΣ', 'Εξουσιοδοτημέν\nο\nπρόσωπο/Νόμιμο\nς Εκπρόσωπος', '0', '-']]
[['Πρόσθετες Επιλογές'], ['Ισχύς Αδείας 6 έτη (Ανέγερση κτιρίων > 5000 τμ)'], ['Τροποποίηση Μελετών']]
[['Προέγκριση για Αναθεώρηση Οικ. Αδείας (ν.4759/2020)', None], ['Α/Α Πράξης', '872466'], ['A/A Αίτησης', '1142754'], ['Περιγραφή έργου', 'COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ\nΑΔΕΙΑΣ ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΣΧΕΔΙΑΣΗΣ\nΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ ΤΡΕΙΣ\nΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ ΒΟΗΘΗΤΙΚΩΝ\nΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ\nΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ ΣΤΟΙΧΕΙΩΝ,\nΠΕΡΓΚΟΛΩΝ, ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ ΚΑΙ ΚΟΠΗ ΔΕΝΤΡΩΝ, ΣΤΟ OIKOΠEΔO A-\nΠ4.17.1 TOY Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ'], ['Ημ/νία έκδοσης πράξης', '24/11/2023'], ['Ισχύει έως', '14/07/2024'], ['Ηλ. κλειδί αίτησης', 'F1CA23CCB3404E5E'], ['ΑΔΑ', 'Ρ73Δ46Ψ842-2ΑΘ'], ['Μεταγενέστερος έλεγχος Οικ. Αδείας (ν.4759/2020)', None], ['Α/Α Πράξης', '795784'], ['A/A Αίτησης', '1142610'], ['Περιγραφή έργου', "COMMERCIAL HUB: ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ\nΓΙΑ ΑΛΛΑΓΗ ΓΕΝΙΚΟΥ ΕΠΙΒΛΕΠΟΝΤΑ, ΕΠΙΒΛΕΠΟΝΤΑ ΣΤΑΤΙΚΩΝ, ΕΠΙΒΛΕΠΟΝΤΑ\nΣΥΝΤΟΝΙΣΜΟΥ ΜΕΤΡΩΝ ΑΣΦΑΛΕΙΑΣ & ΥΓΕΙΑΣ ΚΑΤΑ ΤΑ ΟΡΙΖΟΜΕΝΑ ΣΤΟ ΠΔ 305/1996\n(Α'212) ΚΑΙ ΕΠΙΒΛΕΠΟΝΤΑ ΕΦΑΡΜΟΓΗΣ ΧΡΟΝΙΚΟΥ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΥ"], ['Ημ/νία έκδοσης πράξης', '13/09/2023'], ['Ισχύει έως', '14/07/2024'], ['Ηλ. κλειδί αίτησης', '131713AAB05E8D5C'], ['ΑΔΑ', ''], ['Αναθεώρηση Οικ. Αδείας ΧΩΡΙΣ μεταβολή κάλυψης/δόμησης/όγκου (ν.4759/2020)', None], ['Α/Α Πράξης', '795768'], ['A/A Αίτησης', '1140784'], ['Περιγραφή έργου', "COMMERCIAL HUB: ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 748232/2023 ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ\nΓΙΑ ΑΛΛΑΓΗ ΓΕΝΙΚΟΥ ΕΠΙΒΛΕΠΟΝΤΑ, ΕΠΙΒΛΕΠΟΝΤΑ ΣΤΑΤΙΚΩΝ, ΕΠΙΒΛΕΠΟΝΤΑ\nΣΥΝΤΟΝΙΣΜΟΥ ΜΕΤΡΩΝ ΑΣΦΑΛΕΙΑΣ & ΥΓΕΙΑΣ ΚΑΤΑ ΤΑ ΟΡΙΖΟΜΕΝΑ ΣΤΟ ΠΔ 305/1996\n(Α'212) ΚΑΙ ΕΠΙΒΛΕΠΟΝΤΑ ΕΦΑΡΜΟΓΗΣ ΧΡΟΝΙΚΟΥ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΥ"], ['Ημ/νία έκδοσης πράξης', '13/09/2023'], ['Ισχύει έως', '14/07/2024'], ['Ηλ. κλειδί αίτησης', '964411FBBEAF42BD'], ['ΑΔΑ', 'Ψ5ΙΑ46Ψ842-2ΓΥ']]
[['Μεταγενέστερος έλεγχος Οικ. Αδείας (ν.4759/2020)', None], ['Α/Α Πράξης', '751858'], ['A/A Αίτησης', '1083998'], ['Περιγραφή έργου', 'COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ\nΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ\nΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ\nΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ\nΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ\nΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ\nΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1\nΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ'], ['Ημ/νία έκδοσης πράξης', '19/07/2023'], ['Ισχύει έως', '14/07/2024'], ['Ηλ. κλειδί αίτησης', 'AE7A068DD5D82C4B'], ['ΑΔΑ', ''], ['Οικοδομική Άδεια (ν.4759/2020)', None], ['Α/Α Πράξης', '748232'], ['A/A Αίτησης', '1077616'], ['Περιγραφή έργου', 'COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ\nΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ\nΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ\nΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ\nΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ\nΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ\nΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1\nΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ'], ['Ημ/νία έκδοσης πράξης', '14/07/2023'], ['Ισχύει έως', '14/07/2024'], ['Ηλ. κλειδί αίτησης', 'D17FC8D458402F46'], ['ΑΔΑ', 'ΨΖΤ946Ψ842-ΑΚΒ'], ['Προέγκριση Οικοδομικής Αδείας (ν.4759/2020)', None], ['Α/Α Πράξης', '688591'], ['A/A Αίτησης', '981081'], ['Περιγραφή έργου', 'COMMERCIAL HUB: ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ ΚΑΙ ΚΑΤΑΣΚΕΥΗΣ ΤΟΙΧΕΙΩΝ ΑΝΤΙΣΤΗΡΙΞΗΣ-ΑΔΕΙΑ\nΚΟΠΗΣ ΔΕΝΤΡΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΚΤΗΡΙΟΥ ΕΙΔΙΚΗΣ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ\nΣΧΕΔΙΑΣΗΣ ΕΜΠΟΡΙΚΟΥ ΚΕΝΤΡΟΥ, ΓΡΑΦΕΙΩΝ ΚΑΙ ΕΜΠΟΡΙΚΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ, ΜΕ\nΤΡΕΙΣ ΟΡΟΦΟΥΣ, ΤΡΙΑ ΙΣΟΓΕΙΑ ΕΠΙΠΕΔΑ ΚΑΙ ΕΞΙ ΚΛΙΜΑΚΩΤΑ ΥΠΟΓΕΙΑ ΕΠΙΠΕΔΑ\nΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ, ΘΕΣΕΩΝ ΣΤΑΘΜΕΥΣΗΣ ΚΑΙ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ\nΕΓΚΑΤΑΣΤΑΣΕΩΝ, ΜΕ ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ ΚΑΙ ΚΑΤΑΣΚΕΥΗ ΥΔΑΤΙΝΩΝ\nΣΤΟΙΧΕΙΩΝ, ΠΕΡΓΚΟΛΩΝ,ΣΤΕΓΑΣΤΡΩΝ, ΗΛΙΑΚΩΝ ΑΙΘΡΙΩΝ, ΣΤΟ ΟΙΚΟΠΕΔΟ Α-Π4.17.1\nΤΟΥ Ο.Τ. Α-Π4.17 ΤΟΥ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΟΛΟΥ ΕΛΛΗΝΙΚΟΥ- ΑΓΙΟΥ ΚΟΣΜΑ'], ['Ημ/νία έκδοσης πράξης', '18/05/2023'], ['Ισχύει έως', '18/05/2025'], ['Ηλ. κλειδί αίτησης', 'F1DFE69589C4E4D1'], ['ΑΔΑ', '6ΘΙΦ46Ψ842-57Ω']]
[['Εγκρίσεις Φορέων', None, None, None], ['Τύπος Έγκρισης', 'Αρμόδια Υπηρεσία', 'Αρ. Πρωτ.', 'Ημ/νία']]
[['Έγκριση Κυκλοφοριακής\nσύνδεσης', 'ΥΠΟΥΡΓΕΙΟ ΥΠΟΔΟΜΩΝ ΚΑΙ ΜΕΤΑΦΟΡΩΝ/ΔΙΕΥΘΥΝΣΗ ΟΔΙΚΩΝ\nΥΠΟΔΟΜΩΝ (ΔΟΥ)', '314964', '20/10/2023'], ['Άλλες εγκρίσεις', 'ΑΠΟΦΑΣΗ ΠΕΡΙΦΕΡΕΙΑΡΧΗ/Χορήγηση Παρέκκλισης Απαίτησης\nΦυσικού Φωτισμού & Αερισμού', '1451626', '24/11/2023'], ['Έγκριση Κυκλοφοριακής\nσύνδεσης', 'ΥΠΟΥΡΓΕΙΟ ΥΠΟΔΟΜΩΝ ΚΑΙ ΜΕΤΑΦΟΡΩΝ/ΔΙΕΥΘΥΝΣΗ ΟΔΙΚΩΝ\nΥΠΟΔΟΜΩΝ (ΔΟΥ)', '20003', '22/06/2023'], ['Άλλες εγκρίσεις', 'ΕΔΑ', '80014676', '28/09/2023'], ['Άλλες εγκρίσεις', 'ΔΕΔΑ', 'Μ11069332-1', '13/10/2023'], ['Άλλες εγκρίσεις', 'ΥΠΕΝ/ΔΑΟΚΑ/Υπουργική Απόφαση', '26338934', '10/03/2023'], ['Έγκριση\nΚΕ.Σ.Α./ΚΕ.Σ.Α.Α./ΚΕ.Σ.\nΑ.ΜΑ.Θ.', 'ΚΕ.Σ.Α.', '110/3', '13/02/2023'], ['Έγκριση\nΚΕ.Σ.Α./ΚΕ.Σ.Α.Α./ΚΕ.Σ.\nΑ.ΜΑ.Θ.', 'ΚΕ.Σ.Α.', '638/13', '16/10/2023'], ['Μελέτη\nΠεριβαλλοντικών\nΕπιπτώσεων', 'ΥΠΕΝ/ΓΕΝΙΚΗ ΔΙΕΥΘΥΝΣΗ ΠΕΡΙΒΑΛΛΟΝΤΙΚΗΣ ΠΟΛΙΤΙΚΗΣ/\nΔΙΕΥΘΥΝΣΗ ΠΕΡΙΒΑΛΛΟΝΤΙΚΗΣ ΑΔΕΙΟΔΟΤΗΣΗΣ', '72739/4751', '05/07/2023'], ['Έγκριση Υψομέτρου', 'ΥΠΕΝ/ΓΕΝΙΚΗ ΓΡΑΜΜΑΤΕΙΑ ΧΩΡΙΚΟΥ ΣΧΕΔΙΑΣΜΟΥ ΚΑΙ ΑΣΤΙΚΟΥ\nΠΕΡΙΒΑΛΛΟΝΤΟΣ/ ΓΡΑΦΕΙΟ ΕΛΛΗΝΙΚΟΥ', '35540/225', '31/03/2023'], ['Υποσταθμός ρεύματος', 'ΔΕΔΔΗΕ', '415230', '06/11/2023'], ['Έγκριση ΣΥ.ΠΟ.Θ.Α. /\nKΕ.ΣΥ.ΠΟ.Θ.Α.', 'ΚΕ.ΣΥ.ΠΟ.ΘΑ', '138', '20/12/2022']]
[['Στοιχεία Διαγράμματος Κάλυψης', None, None, None, None], ['Εμβαδόν οικοπέδου', '122.230,782', None, None, None], ['', 'ΥΦΙΣΤΑΜΕΝΑ', 'ΝΟΜΙΜΟΠΟΙΟΥ\nΜΕΝΑ', 'ΠΡΑΓΜΑΤΟΠΟΙΟ\nΥΜΕΝΑ', 'ΣΥΝΟΛΟ'], ['Εμβ. κάλυψης κτιρίου', '0', '0', '72.818,325', '72.818,325'], ['Εμβ. δόμησης κτιρίου', '0', '0', '183.824,82', '183.824,82'], ['Εμβ. ακάλυπτου χώρου οικοπέδου', '0', '0', '49.412,457', '49.412,457'], ['Όγκος κτιρίου (άνω εδάφους)', '0', '0', '1.129.890,031', '1.129.890,031'], ['Μέγιστο ύψος κτιρίου', '0', '0', '19,5', '19,5'], ['Αριθμός Ορόφων', '0', '0', '6', '6'], ['Αριθμός Θέσεων Στάθμευσης', '0', '0', '4.104', '4.104']]
[['Χρήσεις ανά όροφο', 'Ισόγειο', 'Λοιπές Χρήσεις'], [None, 'Ισόγειο', 'Λοιπές Χρήσεις'], [None, 'Ισόγειο', 'Λοιπές Χρήσεις'], [None, '1ος όροφος', 'Λοιπές Χρήσεις'], [None, '2ος όροφος', 'Λοιπές Χρήσεις'], [None, '3ος όροφος', 'Λοιπές Χρήσεις'], [None, 'Ισόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, '3ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, None, 'Βοηθητική Χρήση'], [None, '3ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, '1ο υπόγειο', 'Γραφεία'], [None, '6ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, None, 'Βοηθητική Χρήση'], [None, '5ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, None, 'Βοηθητική Χρήση'], [None, '4ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, None, 'Βοηθητική Χρήση'], [None, '2ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, None, 'Βοηθητική Χρήση'], [None, '1ο υπόγειο', 'Στάθμευση αυτοκινήτων και πρατήρια\nυγρών καυσίμων'], [None, None, 'Βοηθητική Χρήση'], [None, 'Ισόγειο', 'Εμπόριο'], [None, None, 'Γραφεία'], [None, 'Ισόγειο', 'Εμπόριο'], [None, None, 'Εμπόριο'], [None, None, 'Γραφεία'], [None, 'Ισόγειο', 'Εμπόριο'], [None, None, 'Εμπόριο'], [None, None, 'Εμπόριο'], [None, None, 'Γραφεία'], [None, '1ος όροφος', 'Γραφεία'], [None, None, 'Εμπόριο'], [None, '2ος όροφος', 'Γραφεία'], [None, '3ος όροφος', 'Γραφεία'], [None, '1ο υπόγειο', 'Εμπόριο'], [None, '1ο υπόγειο', 'Λοιπές Χρήσεις'], [None, '1ος όροφος', 'Εμπόριο'], [None, 'Ισόγειο', 'Εμπόριο'], [None, 'Ισόγειο', 'Εμπόριο'], [None, 'Ισόγειο', 'Εμπόριο'], [None, 'Ισόγειο', 'Εμπόριο'], [None, 'Ισόγειο', 'Λοιπές Χρήσεις']]
[['Στοιχεία Δέσμευσης/Εξαγοράς Θέσεων Στάθμευσης', None, None, None], ['Αρ. Πράξης', 'Ημερομηνία', 'Εκδότης', 'Αριθμός\nΘέσεων\nΣτάθμευσης'], ['41834', '27/11/2023', 'ΚΩΝΣΤΑΝΤΙΝΟΣ ΧΡ. ΚΩΝΣΤΑΝΤΙΝΟΥ', '4.104']]

In [18]:
len(all_parsed)

157

In [19]:
for g in all_parsed[:2]:
    # if "Ιδιοκτήτης" in g[2][2]:
    print(g)

[[['Α/Α Πράξης', '1512911'], ['Ημ/νία έκδοσης πράξης', '09/07/2025'], ['Ισχύει έως', '09/07/2029']], [['Στοιχεία έργου', None], ['Περιγραφή\nΈργου/Εγκατάστασης', 'ΑΝΕΓΕΡΣΗ ΥΠΟΓΕΙΟΥ ΥΠΟΣΤΑΘΜΟΥ ΜΕΣΗΣ ΤΑΣΗΣ (20kV) ΔΕΔΔΗΕ ΔΙΑΝΟΜΗΣ\nΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ στο ΟΤ Α-Π4.10'], ['Οδός', 'O.T. Α-Π4.10 ΠΕΡΙΟΧΗΣ Α-Π4, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΓ.ΚΟΣΜΑ'], ['Αρ. από', '-'], ['Αρ. έως', ''], ['Πόλη/Οικισμός', 'ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ. ΚΟΣΜΑ'], ['Δήμος', 'Ελληνικού-Αργυρούπολης'], ['Δημοτική Ενότητα /\nΠεριοχή', 'Περιοχή προς Πολεοδόμηση Α-Π4 - Tομέας VΙΙI "Γειτονιά Επιχειρηματικού Κέντρου\nΛεωφόρου Βουλιαγμένης" του Μ.Π. Ελληνικού-Αγ.Κοσμά'], ['ΟΤ', 'Α-Π4.10'], ['ΚΑΕΚ', '050501505002/0/0επιφ'], ['Ηλ. κλειδί πράξης', '7C700C51C441DE6B'], ['Τύπος Πράξης', 'Οικοδομική Άδεια (ν.4759/2020)'], ['A/A Αίτησης', '2014682'], ['Διαχειριστής Αίτησης', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]']], [['Στοιχεία κυρίου του έργου', None, None, None, None, None], ['Επώνυμο/ία', 'Όνομα', 'Όνομα πατέρα', 'Ιδιότητα', 'Ποσοστό', 'Τύπος\nδικαιώματος'], ['ΕΛΛΗΝΙΚΟ Μ.Α.Ε.', '-', '', 'Ιδιοκτήτης', '0', 'Πλήρης\nκυριότητα'], ['ΝΤΕΓΙΑΝΝΗΣ', 'ΗΛΙΑΣ', 'ΣΩΤΗΡΙΟΣ', 'Εξουσιοδοτημέν\nο\nπρόσωπο/Νόμιμο\nς Εκπρόσωπος', '0', '-'], ['ΕΛΛΗΝΙΚΟ Μ.Α.Ε.', '-', '', 'Επιφανειούχος\n(Ν. 3986/2011)', '100', 'Επιφάνεια']], [['Προέγκριση Οικοδομικής Αδείας (ν.4759/2020)', None], ['Α/Α Πράξης', '1502152'], ['A/A Αίτησης', '1962279'], ['Περιγραφή έργου', 'ΑΝΕΓΕΡΣΗ ΥΠΟΓΕΙΟΥ ΥΠΟΣΤΑΘΜΟΥ ΜΕΣΗΣ ΤΑΣΗΣ (20kV) ΔΕΔΔΗΕ ΔΙΑΝΟΜΗΣ\nΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ στο ΟΤ Α-Π4.10'], ['Ημ/νία έκδοσης πράξης', '02/07/2025'], ['Ισχύει έως', '02/07/2028'], ['Ηλ. κλειδί αίτησης', '0DC7D60328BFF360'], ['ΑΔΑ', '98Η246Ψ842-Ο5Ξ']], [['Εγκρίσεις Φορέων', None, None, None], ['Τύπος Έγκρισης', 'Αρμόδια Υπηρεσία', 'Αρ. Πρωτ.', 'Ημ/νία'], ['Έγκριση\nΚΕ.Σ.Α./ΚΕ.Σ.Α.Α./ΚΕ.Σ.\nΑ.ΜΑ.Θ.', 'ΚΕΝΤΡΙΚΟ ΣΥΜΒΟΥΛΙΟ ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ', '1491292', '24/06/2025'], ['Υποσταθμός ρεύματος', 'ΔΕΔΔΗΕ', '195082', '05/06/2025'], ['Έγκριση Υψομέτρου', 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ & ΕΝΕΡΓΕΙΑΣ ΓΕΝΙΚΗ\nΓΡΑΜΜΑΤΕΙΑ ΧΩΡΙΚΟΥ ΣΧΕΔΙΑΣΜΟΥ ΚΑΙ ΑΣΤΙΚΟΥ\nΠΕΡΙΒΑΛΛΟΝΤΟΣ ΓΡΑΦΕΙΟ ΕΛΛΗΝΙΚΟΥ', '61596/328', '04/06/2025']], [['Στοιχεία Διαγράμματος Κάλυψης', None, None, None, None], ['Εμβαδόν οικοπέδου', '11.106,468', None, None, None], ['', 'ΥΦΙΣΤΑΜΕΝΑ', 'ΝΟΜΙΜΟΠΟΙΟΥ\nΜΕΝΑ', 'ΠΡΑΓΜΑΤΟΠΟΙΟ\nΥΜΕΝΑ', 'ΣΥΝΟΛΟ'], ['Εμβ. κάλυψης κτιρίου', '0', '0', '0', '0'], ['Εμβ. δόμησης κτιρίου', '0', '0', '0', '0'], ['Εμβ. ακάλυπτου χώρου οικοπέδου', '0', '0', '0', '0'], ['Όγκος κτιρίου (άνω εδάφους)', '0', '0', '0', '0'], ['Μέγιστο ύψος κτιρίου', '0', '0', '0', '0'], ['Αριθμός Ορόφων', '0', '0', '0', '0'], ['Αριθμός Θέσεων Στάθμευσης', '0', '0', '0', '0'], ['Χρήσεις ανά όροφο', '1ο υπόγειο', None, 'Λοιπές Χρήσεις', None]], [['ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ', None], ['Μελέτη τοπογραφικού\nδιαγράμματος', 'ΜΑΤΘΑΙΟΥ ΑΓΓΕΛΟΣ (A.M. TEE:84102), ΑΓΡΟΝΟΜΟΣ ΤΟΠΟΓΡΑΦΟΣ ΜΗΧΑΝΙΚΟΣ[2000]'], ['Διάγραμμα Κάλυψης\nΑρχιτεκτονικής Μελέτης', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Αρχιτεκτονική μελέτη', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Στατική μελέτη', 'ΚΟΝΤΙΖΑΣ ΑΘΑΝΑΣΙΟΣ (A.M. TEE:56467), ΠΟΛΙΤΙΚΟΣ ΜΗΧΑΝΙΚΟΣ[1990]'], ['Μελέτη ηλεκτρικών\nεγκαταστάσεων', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ['Μελέτη χρονικού\nπρογραμματισμού', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Μελέτη ενεργητικής\nπυροπροστασίας', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ['Μελέτη παθητικής\nπυροπροστασίας', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]']], [['ΟΜΑΔΑ ΕΠΙΒΛΕΨΗΣ ΕΡΓΟΥ', None], ['Επίβλεψη Αρχιτεκτονικής\nμελέτης (Γενική επίβλεψη)', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Επίβλεψη στατικής\nμελέτης', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Επίβλεψη ηλεκτρικών\nεγκαταστάσεων', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ['Επίβλεψη εγκατάστασης\nπυροπροστασίας', 'ΤΡΙΕΔΡΟΣ ΜΕΛΕΤΗΤΙΚΗ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ (Αρ. ΤΕΕ:2239), ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΝΙΑΡΧΟΣ ΝΙΚΟΛΑΟΣ (A.M. TEE:46709), ΜΗΧΑΝΟΛΟΓΟΣ ΜΗΧΑΝΙΚΟΣ[1985]'], ["Συντονισμός μέτρων\nασφαλείας & υγείας κατά\nτα οριζόμενα στο ΠΔ\n305/1996 (Α'212)", 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]'], ['Εφαρμογή χρονικού\nπρογραμματισμού', 'ΠΟΝΗΡΟΣ ΘΕΟΔΩΡΟΣ (A.M. TEE:138416), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[2015]']], [['ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ', None], ['Συντεταγμένες', '477244.65011430014 4194368.597070529,477255.23346880014 4194262.102065873,477152.707222081\n4194251.5187113727,477141.4624079247 4194357.352256373'], ['', None]]]
[[['Α/Α Πράξης', '1143553'], ['Ημ/νία έκδοσης πράξης', '02/08/2024'], ['Ισχύει έως', '02/08/2027']], [['Στοιχεία έργου', None], ['Περιγραφή\nΈργου/Εγκατάστασης', 'ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ ΠΑΤΑΡΙ, ΥΠΟΓΕΙΟ ΧΩΡΟ\nΣΤΑΘΜΕΥΣΗΣ, ΥΠΟΓΕΙΟ ΜΕ ΚΥΡΙΟΥΣ ΚΑΙ ΒΟΗΘΗΤΙΚΟΥΣ ΧΩΡΟΥΣ, ΚΟΛΥΜΒ. ΔΕΞΑΜΕΝΗ,\nΔΙΑΚΟΣΜΗΤΙΚΗ ΔΕΞΑΜΕΝΗ, ΔΙΑΜΟΡΦΩΣΗ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΩΡΟΥ, ΦΥΛΑΚΙΟ ΚΑΙ ΚΟΠΗ\nΕΝΟΣ ΔΕΝΤΡΟΥ, ΣΤO ΟΙΚΟΠΕΔΟ (1.2.2) ΤΟΥ ΟΙΚΟΔΟΜΙΚΟΥ ΤΕΤΡΑΓΩΝΟΥ ΠΜ-Π1.2'], ['Οδός', 'O.T.ΠΜ-Π1.2 ΠΕΡΙΟΧΗΣ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ.ΚΟΣΜΑ'], ['Αρ. από', '0'], ['Αρ. έως', '0'], ['Πόλη/Οικισμός', 'ΑΛΙΜΟΣ'], ['Δήμος', 'Αλίμου'], ['Δημοτική Ενότητα /\nΠεριοχή', 'ΠΕΡΙΟΧΗ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ.ΚΟΣΜΑ'], ['ΟΤ', 'ΠΜ-Π1.2'], ['ΚΑΕΚ', '050134706003/0/0'], ['Ηλ. κλειδί πράξης', 'C74E4BD8D7038383'], ['Τύπος Πράξης', 'Προέγκριση Οικοδομικής Αδείας (ν.4759/2020)'], ['A/A Αίτησης', '1496596'], ['Διαχειριστής Αίτησης', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ']], [['Στοιχεία κυρίου του έργου', None, None, None, None, None], ['Επώνυμο/ία', 'Όνομα', 'Όνομα πατέρα', 'Ιδιότητα', 'Ποσοστό', 'Τύπος\nδικαιώματος'], ['SUNSET COVE M.A.E', 'SUNSET COVE\nM.A.E', '', 'Ιδιοκτήτης', '100', 'Πλήρης\nκυριότητα'], ['ΤΟΥΖΙΟΥ (ΕΛΛΗΝΙΚΟ ΜΑΕ)', 'ΑΓΓΕΛΙΚΗ', 'ΔΗΜΗΤΡΙΟΣ', 'Εξουσιοδοτημέν\nο\nπρόσωπο/Νόμιμο\nς Εκπρόσωπος', '0', '-']], [['Πρόσθετες Επιλογές'], ['Ισχύς Αδείας 4 έτη (Ανέγερση κτιρίων <5000τμ & Λοιπ.Περιπτώσεις)']], [['Στοιχεία Διαγράμματος Κάλυψης', None, None, None, None], ['Εμβαδόν οικοπέδου', '2.094,011', None, None, None], ['', 'ΥΦΙΣΤΑΜΕΝΑ', 'ΝΟΜΙΜΟΠΟΙΟΥ\nΜΕΝΑ', 'ΠΡΑΓΜΑΤΟΠΟΙΟ\nΥΜΕΝΑ', 'ΣΥΝΟΛΟ']], [['Εμβ. κάλυψης κτιρίου', '0', '0', '575,84', '575,84'], ['Εμβ. δόμησης κτιρίου', '0', '0', '732,54', '732,54'], ['Εμβ. ακάλυπτου χώρου οικοπέδου', '0', '0', '1.518,17', '1.518,17'], ['Όγκος κτιρίου (άνω εδάφους)', '0', '0', '3.412,11', '3.412,11'], ['Μέγιστο ύψος κτιρίου', '0', '0', '7,8', '7,8'], ['Αριθμός Ορόφων', '0', '0', '2', '2'], ['Αριθμός Θέσεων Στάθμευσης', '0', '0', '10', '10'], ['Χρήσεις ανά όροφο', '1ο υπόγειο', None, 'Κατοικίες', None], [None, None, None, 'Βοηθητική Χρήση', None], [None, 'Ισόγειο', None, 'Κατοικίες', None], [None, '1ος όροφος', None, 'Κατοικίες', None]], [['ΑΠΑΙΤΟΥΜΕΝΕΣ ΕΓΚΡΙΣΕΙΣ', None], ['', 'Έγκριση Σ.Α. / Σ.Α. Αιγαίου'], ['X', 'Έγκριση Κ.Ε.Σ.Α./Κ.Ε.Σ.Α.Α./ΚΕ.Σ.Α.ΜΑ.Θ./ΚΕ.Σ.Ε.Α.'], ['', 'Έγκριση ΣΥ.ΠΟ.Θ.Α. / KΕ.ΣΥ.ΠΟ.Θ.Α.'], ['', 'Έγκριση Δασικής Υπηρεσίας'], ['X', 'Έγκριση Εφορείας Προϊστορικών & Κλασικών Αρχαιοτήτων'], ['', 'Έγκριση Εφορείας Βυζαντινών Αρχαιοτήτων'], ['', 'Έγκριση Εφορείας Νεωτέρων Μνημείων'], ['', 'Έγκριση Εφορείας Αρχαιοτήτων'], ['', 'Έγκριση οριοθέτησης υδατορέματος'], ['', 'Έγκριση Υπηρεσίας Πολιτ. Αεροπορίας'], ['', 'Άλλες εγκρίσεις'], ['', 'Έγκριση ΠΕ.ΣΥ.ΠΟ.Θ.Α.'], ['', 'Έγκριση ΝΕΧΩΠ για γη υψηλής παραγωγικότητας'], ['', 'Έγκριση Κυκλοφοριακής σύνδεσης'], ['', 'Έγκριση αρμόδιου φορέα'], ['', 'Έγκριση ΔΕΗ για απόσταση από καλώδια Υψηλής Τάσης'], ['X', 'Έγκριση Υψομέτρου'], ['', 'Έγκριση Οριοθέτησης Αιγιαλού'], ['', 'Πρωτόκολλο αδυνάτου τακτοποίησης(§3α αρθ.36-όμορα μη οικοδομ.)'], ['', 'Κύρωση δικτύου κοινοχρήστων χώρων(§3γ αρθ.36-δίκτυο μη κυρωμένο)']], [['ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ', None], ['Μελέτη τοπογραφικού\nδιαγράμματος', 'Σ. ΚΑΤΣΩΛΗΣ - Δ. ΜΠΙΛΑΛΗΣ Ο.Ε. δ.τ. XYZ ΤΟΠΟΓΡΑΦΙΚΕΣ ΜΕΛΕΤΕΣ (Αρ. ΤΕΕ:25260),\nΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ'], [None, 'ΚΑΤΣΩΛΗΣ ΣΤΕΦΑΝΟΣ (A.M. TEE:66661), ΑΓΡΟΝΟΜΟΣ ΤΟΠΟΓΡΑΦΟΣ ΜΗΧΑΝΙΚΟΣ[1993]'], ['Διάγραμμα Κάλυψης\nΑρχιτεκτονικής Μελέτης', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Αρχιτεκτονική μελέτη', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Μελέτη χρονικού\nπρογραμματισμού', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Μελέτη παθητικής\nπυροπροστασίας', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]'], ['Λοιπές Εργασίες - Μελέτες', 'ISV ΤΕΧΝΙΚΗ- ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΕΙΑ Δ.Τ ISV (Αρ. ΤΕΕ:2026), ΤΕΧΝΙΚΗ\nΕΤΑΙΡΕΙΑ'], [None, 'ΙΩΑΝΝΟΥ ΧΑΡΑΛΑΜΠΟΣ (A.M. TEE:18159), ΑΡΧΙΤΕΚΤΟΝΑΣ ΜΗΧΑΝΙΚΟΣ[1972]']], [['Ομάδα Ελέγχου Έργου', None], ["Τοπογραφικό διάγραμμα Ε.Γ.Σ.Α. '87", 'ΠΑΠΑΣΠΥΡΟΥ ΠΕΤΡΟΣ'], ['Διάγραμμα κάλυψης Αρχιτεκτονικής\nΜελέτης', 'ΤΣΙΤΣΟΥΛΑΣ-ΓΙΑΓΚΟΥΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ']]]

In [20]:
pd.DataFrame(all_parsed)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,"[[Α/Α Πράξης, 1512911], [Ημ/νία έκδοσης πράξης...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Προέγκριση Οικοδομικής Αδείας (ν.4759/2020),...","[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[ΟΜΑΔΑ ΕΠΙΒΛΕΨΗΣ ΕΡΓΟΥ, None], [Επίβλεψη Αρχι...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None,None,None,None,None,None
1,"[[Α/Α Πράξης, 1143553], [Ημ/νία έκδοσης πράξης...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Πρόσθετες Επιλογές], [Ισχύς Αδείας 4 έτη (Αν...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[Εμβ. κάλυψης κτιρίου, 0, 0, 575,84, 575,84],...","[[ΑΠΑΙΤΟΥΜΕΝΕΣ ΕΓΚΡΙΣΕΙΣ, None], [, Έγκριση Σ....","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[Ομάδα Ελέγχου Έργου, None], [Τοπογραφικό διά...",None,None,None,None,None,None,None,None,None
2,"[[Α/Α Πράξης, 878905], [Ημ/νία έκδοσης πράξης,...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Πρόσθετες Επιλογές], [Ισχύς Αδείας 6 έτη (Αν...",[[Προέγκριση για Αναθεώρηση Οικ. Αδείας (ν.475...,[[Μεταγενέστερος έλεγχος Οικ. Αδείας (ν.4759/2...,"[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[Έγκριση Κυκλοφοριακής\nσύνδεσης, ΥΠΟΥΡΓΕΙΟ Υ...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[Χρήσεις ανά όροφο, Ισόγειο, Λοιπές Χρήσεις],...",[[Στοιχεία Δέσμευσης/Εξαγοράς Θέσεων Στάθμευση...,"[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[, ΚΙΡΙΜΛΙΔΗΣ ΔΗΜΗΤΡΙΟΣ (A.M. TEE:15039), ΜΗΧ...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None
3,"[[Α/Α Πράξης, 1038346], [Ημ/νία έκδοσης πράξης...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Πρόσθετες Επιλογές], [α. Δοκιμαστικές τομές ...","[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None,None,None,None,None,None,None,None,None
4,"[[Α/Α Πράξης, 825961], [Ημ/νία έκδοσης πράξης,...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Πρόσθετες Επιλογές], [Ισχύς αδείας 1 έτος (Ε...","[[Στοιχεία Διαγράμματος Κάλυψης, None], [Εμβαδ...","[[, ΥΦΙΣΤΑΜΕΝΑ, ΝΟΜΙΜΟΠΟΙΟΥ\nΜΕΝΑ, ΠΡΑΓΜΑΤΟΠΟΙ...","[[ΑΠΑΙΤΟΥΜΕΝΕΣ ΕΓΚΡΙΣΕΙΣ, None], [, Έγκριση Σ....","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[Εφαρμογή χρονικού\nπρογραμματισμού, 314 ARCH...","[[Ομάδα Ελέγχου Έργου, None], [Τοπογραφικό διά...",None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,"[[Α/Α Πράξης, 1502152], [Ημ/νία έκδοσης πράξης...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Πρόσθετες Επιλογές], [Ισχύς Αδείας 4 έτη (Αν...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[Εμβ. κάλυψης κτιρίου, 0, 0, 0, 0], [Εμβ. δόμ...","[[ΑΠΑΙΤΟΥΜΕΝΕΣ ΕΓΚΡΙΣΕΙΣ, None], [, Έγκριση Σ....","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[Ομάδα Ελέγχου Έργου, None], [Τοπογραφικό διά...",None,None,None,None,None,None,None,None,None
153,"[[Α/Α Πράξης, 842969], [Ημ/νία έκδοσης πράξης,...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Προέγκριση Οικοδομικής Αδείας (ν.4759/2020),...","[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...",[[Στοιχεία Δέσμευσης/Εξαγοράς Θέσεων Στάθμευση...,"[[Μελέτη τοπογραφικού\nδιαγράμματος, Σ. ΚΑΤΣΩΛ...","[[Επίβλεψη ηλεκτρικών\nεγκαταστάσεων, ΚΑΡΑΓΙΑΝ...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None,None,None,None,None
154,"[[Α/Α Πράξης, 1178809], [Ημ/νία έκδοσης πράξης...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Πρόσθετες Επιλογές], [Ισχύς Αδείας 6 έτη (Αν...",[[Προέγκριση για Αναθεώρηση Οικ. Αδείας (ν.475...,"[[Οικοδομική Άδεια (ν.4759/2020), None], [Α/Α ...","[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[Αριθμός Ορόφων, 0, 0, 5, 5], [Αριθμός Θέσεων...",[[Στοιχεία Δέσμευσης/Εξαγοράς Θέσεων Στάθμευση...,"[[Στοιχεία υφισταμένου κτίσματος, None, None, ...","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[, ΧΑΤΖΗΑΓΓΕΛΙΔΗΣ ΠΑΥΛΟΣ (A.M. TEE:93794), ΑΡ...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None
155,"[[Α/Α Πράξης, 827131], [Ημ/νία έκδοσης πράξης,...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Προέγκριση Οικοδομικής Αδείας (ν.4759/2020),...","[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[Στοιχεία υφισταμένου κτίσματος, None, None, ...","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[, ΚΑΡΑΓΙΑΝΝΗ ΦΩΤΕΙΝΗ (A.M. TEE:112926), ΠΟΛΙ...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None,None,None,None,None
156,"[[Α/Α Πράξης, 836266], [Ημ/νία έκδοσης πράξης,...","[[Στοιχεία έργου, None], [Περιγραφή\nΈργου/Εγκ...","[[Στοιχεία κυρίου του έργου, None, None, None,...","[[Προέγκριση Οικοδομικής Αδείας (ν.4759/2020),...","[[Εγκρίσεις Φορέων, None, None, None], [Τύπος ...","[[Στοιχεία Διαγράμματος Κάλυψης, None, None, N...","[[Στοιχεία υφισταμένου κτίσματος, None, None, ...","[[ΟΜΑΔΑ ΜΕΛΕΤΗΣ ΕΡΓΟΥ, None], [Μελέτη τοπογραφ...","[[, ΧΑΤΖΗΑΓΓΕΛΙΔΗΣ ΠΑΥΛΟΣ (A.M. TEE:93794), ΑΡ...","[[ΕΝΤΟΠΙΣΜΟΣ ΑΚΙΝΗΤΟΥ, None], [Συντεταγμένες, ...",None,None,None,None,None,None,None,None

In [21]:
def clean_parsed_to_dataframe(all_parsed, pdfs):
    """
    Cleans the all_parsed data and creates a structured DataFrame.

    Args:
        all_parsed: List of parsed PDF documents (each is a list of tables)
        pdfs: List of PDF file paths (to extract ADA identifiers)

    Returns:
        pandas DataFrame with cleaned building permit data
    """

    def find_value(tables, key):
        """Search for a key in tables and return its value."""
        for table in tables:
            for row in table:
                if row and len(row) >= 2 and row[0]:
                    clean_key = row[0].replace('\n', ' ').strip() if row[0] else ''
                    if key.lower() in clean_key.lower():
                        return row[1].replace('\n', ' ').strip() if row[1] else None
        return None

    def find_coverage_value(tables, key, column_idx=4):
        """Find values in the coverage diagram table (ΣΥΝΟΛΟ column)."""
        for table in tables:
            for row in table:
                if row and len(row) >= column_idx + 1 and row[0]:
                    clean_key = row[0].replace('\n', ' ').strip() if row[0] else ''
                    if key.lower() in clean_key.lower():
                        for idx in [column_idx, 3, 2, 1]:
                            if len(row) > idx and row[idx]:
                                return row[idx].replace('\n', ' ').strip() if row[idx] else None
        return None

    def find_owner_info(tables):
        """Extract owner information from the owner table."""
        owners = []
        for table in tables:
            if table and len(table) > 1:
                header = table[0] if table[0] else []
                if any('κυρίου' in str(cell).lower() for cell in header if cell):
                    for row in table[1:]:
                        if row and len(row) >= 4:
                            if row[0] and 'Επώνυμο' not in str(row[0]):
                                name = row[0].replace('\n', ' ').strip() if row[0] else ''
                                role = row[3].replace('\n', ' ').strip() if len(row) > 3 and row[3] else ''
                                if name and 'Ιδιοκτήτης' in role:
                                    owners.append(name)
        return '; '.join(owners) if owners else None

    def find_coordinates(tables):
        """Extract coordinates from the location table."""
        for table in tables:
            for row in table:
                if row and len(row) >= 2 and row[0]:
                    if 'Συντεταγμένες' in str(row[0]):
                        return row[1].strip() if row[1] else None
        return None

    records = []

    for idx, (doc, pdf_path) in enumerate(zip(all_parsed, pdfs)):
        if not doc:
            continue

        ada = os.path.basename(pdf_path).replace('.pdf', '')

        record = {
            'ada': ada,
            'aa_praxis': find_value(doc, 'Α/Α Πράξης'),
            'issue_date': find_value(doc, 'Ημ/νία έκδοσης'),
            'valid_until': find_value(doc, 'Ισχύει έως'),
            'description': find_value(doc, 'Περιγραφή'),
            'address': find_value(doc, 'Οδός'),
            'city': find_value(doc, 'Πόλη/Οικισμός'),
            'municipality': find_value(doc, 'Δήμος'),
            'area': find_value(doc, 'Δημοτική Ενότητα'),
            'ot': find_value(doc, 'ΟΤ'),
            'kaek': find_value(doc, 'ΚΑΕΚ'),
            'permit_type': find_value(doc, 'Τύπος Πράξης'),
            'owner': find_owner_info(doc),
            'plot_area': find_value(doc, 'Εμβαδόν οικοπέδου'),
            'coverage_area': find_coverage_value(doc, 'κάλυψης κτιρίου'),
            'building_area': find_coverage_value(doc, 'δόμησης κτιρίου'),
            'uncovered_area': find_coverage_value(doc, 'ακάλυπτου χώρου'),
            'volume': find_coverage_value(doc, 'Όγκος κτιρίου'),
            'max_height': find_coverage_value(doc, 'Μέγιστο ύψος'),
            'floors': find_coverage_value(doc, 'Αριθμός Ορόφων'),
            'parking_spots': find_coverage_value(doc, 'Θέσεων Στάθμευσης'),
            'coordinates': find_coordinates(doc),
        }

        records.append(record)

    df = pd.DataFrame(records)

    # Convert numeric columns
    numeric_cols = ['plot_area', 'coverage_area', 'building_area', 'uncovered_area',
                    'volume', 'max_height', 'floors', 'parking_spots']
    for col in numeric_cols:
        if col in df.columns:
            df[col] = df[col].str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Convert date columns
    date_cols = ['issue_date', 'valid_until']
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], format='%d/%m/%Y', errors='coerce')

    return df


# Usage:
# df_permits = clean_parsed_to_dataframe(all_parsed, pdfs)
# df_permits.head()

In [22]:
df_permits = clean_parsed_to_dataframe(all_parsed, pdfs)
df_permits.head()

,ada,aa_praxis,issue_date,valid_until,description,address,city,municipality,area,ot,...,owner,plot_area,coverage_area,building_area,uncovered_area,volume,max_height,floors,parking_spots,coordinates
0,9Γ0Ξ46Ψ842-Γ7Ω,1512911,2025-07-09,2029-07-09,ΑΝΕΓΕΡΣΗ ΥΠΟΓΕΙΟΥ ΥΠΟΣΤΑΘΜΟΥ ΜΕΣΗΣ ΤΑΣΗΣ (20kV...,"O.T. Α-Π4.10 ΠΕΡΙΟΧΗΣ Α-Π4, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛ...",ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ΑΓ. ΚΟΣΜΑ,Ελληνικού-Αργυρούπολης,"Περιοχή προς Πολεοδόμηση Α-Π4 - Tομέας VΙΙI ""Γ...","Περιοχή προς Πολεοδόμηση Α-Π4 - Tομέας VΙΙI ""Γ...",...,ΕΛΛΗΝΙΚΟ Μ.Α.Ε.,11106.468,0.000,0.00,0.000,0.000,0.0,0.0,0.0,"477244.65011430014 4194368.597070529,477255.23..."
1,6ΥΩ246Ψ842-16Μ,1143553,2024-08-02,2027-08-02,ΑΝΕΓΕΡΣΗ ΝΕΑΣ ΔΙΩΡΟΦΗΣ ΑΥΤΟΤΕΛΟΥΣ ΚΑΤΟΙΚΙΑΣ ΜΕ...,"O.T.ΠΜ-Π1.2 ΠΕΡΙΟΧΗΣ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛ...",ΑΛΙΜΟΣ,Αλίμου,"ΠΕΡΙΟΧΗ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ...","ΠΕΡΙΟΧΗ ΠΜ-Π1, ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ ...",...,SUNSET COVE M.A.E,2094.011,575.840,732.54,1518.170,3412.110,7.8,2.0,10.0,None
2,ΨΣΖΞ46Ψ842-86Ω,878905,2023-11-30,2024-07-14,COMMERCIAL HUB: Β ΑΝΑΘΕΩΡΗΣΗ ΤΗΣ Α/Α ΠΡΑΞΗΣ 74...,"ΠΕΡΙΟΧΗ ΠΡΟΣ ΠΟΛΕΟΔΟΜHΣΗ Α-Π4,ΤΟΜΕΑΣ VI",ΕΛΛΗΝΙΚΟ,Ελληνικού-Αργυρούπολης,ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΓ.ΚΟΣΜΑ,ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΓ.ΚΟΣΜΑ,...,ΕΛΛΗΝΙΚΟ Μ.Α.Ε.; LAMDA VOULIAGMENIS S.M.S.A.,122230.782,72818.325,183824.82,49412.457,1129890.031,19.5,6.0,4104.0,"477410.6764880197 4193678.0331894006,477426.55..."
3,ΡΗΘΞ46Ψ842-ΠΑΑ,1038346,2024-04-25,2025-04-25,ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΠΕΝΕΤΡΟΜΕΤΡΗΣΕΩΝ ΓΙΑ ΤΗΝ ΕΚΠ...,ΑΝΩΝΥΜΗ,ΕΛΛΗΝΙΚΟ,Ελληνικού-Αργυρούπολης,None,None,...,ALAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"475050.5884345101 4194092.371518077,475104.034..."
4,6Φ9Ψ46Ψ842-ΜΞ2,825961,2023-10-11,2026-10-11,"ΑΔΕΙΑ ΕΚΣΚΑΦΩΝ, ΜΕ ΣΚΟΠΟ ΤΗΝ ΑΝΕΓΕΡΣΗ ΝΕΟΥ ΣΥΓ...",ΑΝΩΝΥΜΟΣ (Ο.Τ. Α-Π6.10),ΑΛΙΜΟΣ,Αλίμου,ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ,ΜΗΤΡΟΠΟΛΙΤΙΚΟΣ ΠΟΛΟΣ ΕΛΛΗΝΙΚΟΥ-ΑΓΙΟΥ ΚΟΣΜΑ,...,ΕΛΛΗΝΙΚΟ Μ.Α.Ε,6190.667,0.000,0.00,0.000,0.000,0.0,0.0,0.0,None

In [23]:
df_permits.to_csv("permits_ellhniko.csv", index=False)